### ISSUE TITLE
Policies for the EKS CIS  Rules

### ISSUE THREAD

**Issue by karthik012** [kyverno/policies#100]
Any idea , where can we find the policies related/similar to the below rules:
1. Ensure that the cluster-admin role is only used where required
2. Minimize wildcards use in roles and clusterroles

I wanted to have a policy for 3. Minimize access to create pods	, for which I could tweak this:
https://kyverno.io/policies/other/block_updates_deletes/

But could not find policies/related to 1 & 2. Any leads would be helpful.

Thanks in advance.

**Comment by chipzoller** [comment]
The CIS benchmarks are Kubernetes cluster best practices/configurations and not really policy opportunities in most cases. Kyverno can be used to assist in these regards, but you still have to define what you want in your environment. So for item number one, what does "where required" mean for you? Similar with two.

**Comment by chipzoller** [comment]
Closing if nothing further.
