### ISSUE TITLE
Improve Policy "drop-all-capabilities"

### ISSUE THREAD

**Issue by kaihil** [kyverno/policies#109]
I just found out, to fulfill the policy `drop-all-capabilities` it is important to write `ALL` in upper case. `all` in lower case won't satisfy it.

Most documentation/blog posts (about dropping all capabilities) I googled, write:
```
capabilities:
  drop:
    - all
```

Therefore, it would be nice if either both `all` and `ALL` are valid or the message contains a corresponding hint that `ALL` in upper case has to be used.

**Comment by chipzoller** [comment]
Thanks for the issue, @kaihil . I have an open PR where I've included a better message which states `ALL` must be written in all caps.

**Comment by chipzoller** [comment]
This has been further enhanced with new logic that works with Kyverno 1.4.3.

**Comment by kaihil** [comment]
Nice, thank you!

**Comment by joebowbeer** [comment]
To be clear, the spec and the k8s code both require "ALL" (caps)
