### ISSUE TITLE
disallow-privileged-containers: simplify CEL expressions

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#1096]
See: https://github.com/kyverno/policies/issues/1058

**Comment by epasham** [comment]
Please assign this to me. am working on it. Thank You

**Comment by epasham** [comment]
I have updated the policy. Link to the policy https://github.com/epasham/policies/blob/main/pod-security-cel/baseline/disallow-privileged-containers/disallow-privileged-containers.yaml

Kindly review the changes and confirm that changes look good then i will submit the pull request

**Comment by epasham** [comment]
Chainsaw tests are run and find below the test summary
<img width="357" alt="image" src="https://github.com/user-attachments/assets/53702d93-cf48-45c7-8bd5-5cf0961bc992">

**Comment by epasham** [comment]
PR submitted-> https://github.com/kyverno/policies/pull/1129
