### ISSUE TITLE
restrict-seccomp: simplify CEL expressions

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#1099]
See: https://github.com/kyverno/policies/issues/1058

**Comment by epasham** [comment]
picking up this one

**Comment by epasham** [comment]
Policy is simplified and all test cases are executed. works perfectly. ready to raise pull request

**Comment by JimBugwadia** [comment]
@epasham - is there a PR ready for review?

**Comment by epasham** [comment]
@JimBugwadia - Will submit new PR once https://github.com/kyverno/policies/pull/1127 gets merged

**Comment by epasham** [comment]
PR submitted-> https://github.com/kyverno/policies/pull/1129
