### ISSUE TITLE
Configuration files for HNC use-cases with Kyverno

### ISSUE THREAD

**Issue by pkatira** [kyverno/policies#114]
It would be great if we could have configuration/policy files that were used in the lightning demo - https://www.youtube.com/watch?v=f3LBwIMk0Zs 

This would enable folks to try out Kyverno with an HNC usecase.

**Comment by pkatira** [comment]
@JimBugwadia As per our discussion, created this issue.

**Comment by JimBugwadia** [comment]
Adding the "raw" files I used. Will convert to samples - not sure how to best handle the roles, etc. other than comments in the policies.

[multitenancy.zip](https://github.com/kyverno/policies/files/7079201/multitenancy.zip)

**Comment by chipzoller** [comment]
Were you still planning on converting these, @JimBugwadia ?

**Comment by chipzoller** [comment]
Closing.
