### ISSUE TITLE
[Bug]: Kyverno-policies helm chart has hardcoded Kubernetes version annotations

### ISSUE THREAD

**Issue by sergey198828** [kyverno/policies#1165]
### Kyverno Version

1.12

### Kubernetes Version

1.28

### Kubernetes Platform

Other (specify in description)

### Description

When deploy policies using Kyverno-policies helm chart 3.2.5 I can see Chart.yaml is specified kubeVersion: '>=1.25.0-0' and appVersion: v1.12.5.

When I view effective yaml of policies I see:

    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.23"

There is no value I can change this.

### Steps to reproduce

1. helm repo add kyverno https://kyverno.github.io/kyverno/
2. helm template kyverno/kyverno-policies --version 3.2.5 | grep kyverno.io/kyverno-version
3. helm template kyverno/kyverno-policies --version 3.2.5 | grep kyverno.io/kubernetes-version

### Expected behavior

I would like to have a value in values.yaml using which I can control this behavior

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by realshuting** [comment]
Thanks @sergey198828 for creating the issue.

`kyverno.io/kyverno-version: 1.6.0` should be updated upon each new Kyverno release. Feel free to raise a PR for the fix.


`kyverno.io/kubernetes-version: "1.22-1.23"` should be the Kubernetes versions we tested and verified, they don't seem to be updated though.

**Comment by sergey198828** [comment]
Thanks @realshuting, opened Pull request.
https://github.com/kyverno/kyverno/pull/11258
