### ISSUE TITLE
[Bug] Security Capabilites must omit the CAP prefix which is required by Kyverno policies

### ISSUE THREAD

**Issue by StraysWonderland** [kyverno/policies#1166]
### Kyverno Version

1.11

### Kubernetes Version

1.26

### Kubernetes Platform

EKS

### Description

We have implemented a subset of the best practices policies on our aks cluster.
The issue I'm facing is related to the require-drop-cap-net-raw policy which can be found here [within the kyverno policies repository](https://github.com/kyverno/policies/blob/main/best-practices/require-drop-cap-net-raw/require-drop-cap-net-raw.yaml)

However this policy does only recognize a pod as passing the policy if the capability section is defined as:
```yaml
securityContext:
  capabilities:
    drop:
      - CAP_NET_RAW
```
so with the CAP prefix

According to the official[ kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-capabilities-for-a-container) however, these capabilities should omit the CAP prefix as can be seen here:
![image](https://github.com/user-attachments/assets/71114079-bb30-406e-a113-cc5fbf7af1da)

And the problem is that kyverno does not seem to recognize resources dropping the capabilities in this manner:
```yaml
securityContext:
  capabilities:
    drop: ["NET_RAW"]
```

Ive done a bit of testing on some pods and it seems that pods with the CAP_NET_RAW definition, tough passing the kyverno policy, are not actually dropping the security capabilities while pods with the NET_RAW definition fail kyverno but are correctly dropping the security capability.

Ive also visualised how kyverno fails/passes these different definitions in the kyverno playground via [this test](https://playground.kyverno.io/#/?content=N4IgDg9gNglgxgTxALhAQzDAagUwE4DOMEAdsgAQDWCAbviRAHTED0NAjADomUwkAmFAMJQArgQAu%2BAArR4CbgFscEtPzSrk3cuRJplFfnghgAtHAymSK03jQB3beTQkGqicRIEtJHTsiwcDA4BIzUdHgMzBAsHhJQOBQAIsZg5EIAgtIA%2BgByAKIAKtkAShkA6k7%2BckEhYbT0TKwWUgDmEHgIFABCIRLk0nZwHnAhVeQB8MGh4Y3RLIp8EUSkFOyMAGyMAAzjk7UzDZFNMQQ4ETASXeTK/DCiins10/URUawEogBGAFY4wxRZPwnoEXrNjvN%2BCE4HgYGAPKtyAA%2BUzjHRCDBoL4wWAeEITfCLfpgWE0HE4Vo4fjOYaeAjkeyXAAWEFE/VaMDJJFa5AAZqIoFByMYIP00HBRgRQuRCkycGj0lk8kVShVyBYwFicZcEAAacg4PRfBLUr4IchQ3loAUSfVoQUQez0kkQSVnel8Zzq0iqPj4cgSCAK3kdSkTcWUFT0lymvjUwPOEjmvhSPBW0YTUWGjz2qDmhJqPg8hMAWUuJecElUcEooQVspgzpq5sNnzw%2BIkTI0zkF3pIvushANAA8wKD4uajCYA3LFTkCsUypVfH4dFrcQhGORclmZ93O43M4FzfaCBByDixJI7FJ6Sz7AHz3AIBELakDf3YfjPS4FCvVxYZw9p2rKtEyM6HooaDmm45DXvAE59iGeCKI%2BM44AMEDUgAyv8oiwlc5DYaoAhoHg/B1l4YD/D4Og0PaMDqAiJAAGJoDi%2BE4BktKIhkoh3BIThfBGrTGKIAgUBIeCiPKK7SQk3jjKYuj6Ikwo4AAjqIMDtqYU5mBqVg2HYjj/n4UESHATK0aufi/jZtnkMp7ZnvhkoOY5fi8AIilmZ5fjKUCCokv8pACXSHmrrmkUBVQODXJwIDAMA6laX0jAmPgGieOQAA%2BuXkAA5N0GRCAA0gA4iUADyACquRJIV5AAL7NYlCqrplN4dBQO4SPkWmnh1fj0WIalJPkAAyRT5Aqo2MRoiTDcoUpoJSFAosN6I%2Buxg70oo4j9Pp6HkAABpk84qkup3qpi2Iboww3ITg4rWVtTnkLAkgUO2aWSBlvz/BIjAENRcCMAA2jgYBysodhQEIO1%2BoQ%2Bp8JciP9rt%2BAEPqz6Y8jBAALoQ4T706FCSYxf5ePhaQvn%2Bf50Vk7ZymRtcF3KouFTM45XUaD15AZEmfUAJIkDztmjTJFCJclBoJMo/Yg3hBEIBjUjDsDGrrpcLz6STjCBtkohgNReAABQAAIAJR5QVp0kzdrWJSAuogC5rJ4KMKDoJguCEJ4FAcNw3mCJhwIkMoqhMWgNl6AYF6SMQpiQBHoM0U4aMSOrWOEDZynx2pjYIqYWfjDAUHrRarqRng8zF6wLrDrQABMyDrC32yMC34xka09OecpDcQKX8JYgpw3KSnk/kIl7AAKzbNsXAgDPpgAF4z3Pi/bBs7V%2BbFpiiFvIDsAAzGfADs%2B/%2BVPjwHzoyklPkSQi8/QiFGvMAz4VABUhVr2HCfG%2Bg8nJfB/v/NeEdb7kAXtsAAnNsXUcCW7sGQYvTua9TBQAgK0bIrIJBgDZNkBIdAoAAF5LTWigBIZAfAQzjDOHAfCOp1Y4E1jFXMjpBicnJJSfIBALBQGyoiK0UAzgKm1vdXWIQqZvhMHIx%2Bc5OaqmXI5EkvCEiUjDmIiRB92xqGqiQPMJQICihYuSAgCBJA4EUBQXRslHLSRIBkAgFUxJgAoLsfR4lXE7hIKY0U9jTyONss41xtUzh4C8U4PGA5sb5xUgnL44gEBfAgEAsyFc1pqRSVY9Jw526MDPvPXueB%2B4eWUgQBI0MlIXhILyLOf5VxMJYVcNhHCOrhIIP4wJtCAzSVCbZKR2o8QD08vpRRSiOYLlUdwUwCzuAYGwNjQO5Bg48DjICLCSgVBqA0LHJwhcKCwB4PgfgKcdlUQziuOJudxkfT7g81cVSalgBnvQppCpslVzyWkjJRSSkKmOeQP5BSFStNVh02hW1um9LMf0qSMktojNxNMKZ8jPE82UrMpcrsQDQH4CUEIntvaoHxcwyQEBFDEtcl7HASQcCNJILrOmPsKVXlTLS0lIR2Vu3YaMeEdJ2XNSAA===) using the official kyverno policy and two pods with the different capability syntax.

And the playground test also shows that 
CAP_NET_RAW is passing while
NET_RAW is failing

![image](https://github.com/user-attachments/assets/70308a68-4efa-465a-8611-5b2698723a9e)

### Steps to reproduce

1. Implement the require-cap-net-raw policy - on audit mode ideally
2. deploy a pod that specifies securityContext capabilities drop: CAP_NET_RAW
3. deploy a second pod with the securityContext capabilities drop: NET_RAW

### Expected behavior

Kyverno should allow the 2nd pod with NET_RAW syntax as according to kubernetes this is the correct way to drop the capability.
And likely not accept the CAP_NET_RAW definition as this does not actually seem to achieve what it should within the container.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by epasham** [comment]
Can we modify the policy to support both CAP_NET_RAW and NET_RAW capabilities

**Comment by StraysWonderland** [comment]
that would be an option.
However; My concern is that when specifying CAP_NET_RAW on your kubernetes resources, the pod still has the capabilities that should be dropped.
So while kyverno will say that all is fine and secure; the pod is still vulnerable to i.e. spoofing attacks as pods still have access to the NET_RAW capabilities.

My tests indicate that behaviour but I think ideally someone would need to confirm my suspicion to be sure about this.
If my suspicion is incorrect then allowing both is a suitable solution I believe

**Comment by epasham** [comment]
I have seen in some deployment manifests CAP_NET_RAW is used.  It might be Operating system specific. For now, good option is to allow both CAP_NET_RAW and NET_RAW.

**Comment by epasham** [comment]
The changes are done and tested. will be submitting the pull request shortly. You can verify the changes at the following link -> [https://playground.kyverno.io/#/?content=N4IgDg9gNglgxgTxALhAQzDAagUwE4DOMEAdsgAQDWCAbviRAHTED0NAjADomUwkAmFAMJQArgQAu%2BAArR4CbgFscEtPzSrk3cuRJplFfnghgAtHAymSK03jQB3beTQkGqicRIEtJHTsiwcDA4BIzUdHgMzBAsHhJQOBQAIsZg5EIAgtIA%2BgByAKIAKtkAShkA6uR86fkAMuQ4AB5geCFEpARO/nJBIWG09EysFlIA5hB4CBQAQiES5NJ2cB5wIVW%2BQnXkXeQB8MGh4YPRLIp8Ee1k5OyM7DcADDtHkUMxlKIARvQqIaYXnhROCAbgAmABsplBAHYgTs9r1DgMXicCDgIjAJFNyMp%2BDBRIo4T0Dv0IlFWARPgArHDLCiyfiEwLE55kmL8EJwPAwMAeUgUAB8ph2OiEGDQHxgsA8azA%2BDO8xaMBokpwoxw/Gcy08BHI9gxAAsIKJ5qMlXxRuQAGaiKBQcjGCDzNBwVYEULkQr6nDC9JZPJFUoVcgWMDiyUYhAAGgaeg%2BCQ1HwQ5HZlrQNok0bQtog9h1LQgrtROuqaGDpFUfHw5AkEB9lomat2zsoKh1LgTfA1NecJCTfCkeFTq12jpwJA8WagSYSanN1Yg5AAshjF84JKo4JRQj7PTA8z0k2OKa0dRJ9RpnLay%2BO0JXCA1mkz4kmjCZq17fTkCsUyuUfWGpQQRhyFyUd3wvM89xHQIkyzAgF0lMRJDsKQdUNex5zLCJk1SGMJC5NYS17H0LFRS8zyNUZ9XfKDFDQJM3HIZD4Gfa96zwRRMLPHAFggDUAGUaVELlMXIfjVAENA8H4bcvFlOAfB0GgsxgdReRIAAxW8xFaDItT5cgMlEXEJCcD5m1GYxRAECh8NEb1fHtG0QkUvxTF0fREntHAAEdRBgVpTFfMwQysGw7EcRy/GxDQ4H1Vzop0Fwph9HR3JPI08FdBLEui3gBG8VLcvIdz6SK6KTHwDRtRy4qSvSEp8gyQp8nKtzyAAVWkJJmtaqK/GU2A1MSIrVigWrEuUrlxQSQr%2Brq9y9AMbFxAkFITFFUMJSlA42uipoWjaAFthAABtAByTIvwDX9zsjc7v0DcpzoAXVhebisWzyKEnIRy1vaxCD2vwDpPS5ARACAPmpZZGAIeTGDgf67x1ABqcgoZhiQ4YRgB%2BPgMT%2Bm8UcYCYsCzeyAApTpegBKch0cxmlsfhmlGFxnAwC9ZQ7CgImK0B0IyYpnBqbp966p0UGjo6Cbcvc6W3WOwVgeiqaYBmvpfuRwXGEnSmkeJwHo1VvxDYF/B2dROBhIjfmmmx3GQwAjFiVx4LSbwcmxFFmnacYJo9wkAgDbFbaI2jZ3w8xRhRDAWU8AyAgghgSn6eqdXNdCRRVvWsBNpd6UCFp2nTeUN00DVAUhQ%2ByX0h1/AdRzyQcLfbjyAAAyu/0fwqDvgzD8MY5ASMQAy4TVhQdBMFwQhjo4bh8sEXiGRIZRVDUtBXKWryg%2BIUxIFX1mFKcAmJH5gHG9cr7lr3iBTDPnYYDoqvkwLFs8BOO%2BWHzRpaBBZAoJ7iMBBDsKSow5oLSqJIfe3JVBxhCEVdyB8kEnXYAAVnuPcLgIBUGmAAF6oKBBgrBYIJafRKqIIhwIADMNCYS4NrvVUwBImHuUakkAAko1IQhQ8EwFQedAAVOdPBjRqHkPliVD4giRF4NXlAkhABOe4kYSEgnYGozBIJHhsJKqYKAEBRjZCNBIMAxpsgJDoFAAAvCmNMUAJDID4PWHY1tbaYnto0Jx/5sz2EWGaBIap8jJyzNVAyqYoCohIoPHaLkirBTlu1buj1fw%2BkVMqIJ6oKCROiR9VoagADyJApwlAgI6DSKoCAIEkDgRQOS4IOVyngayScADiVkwAUF0c01pBBQIkDKY6BpUSmmJRaSQJOHVUR4G6U4c2l9CDXw8stD44gEAfAgOI/qz9K5eTWdUzZjRAGMBoegsBeAIE5XcgQBInMdjuRcWfBQ/V3EiQQF4nxtcJlJwGUMpx1YWljMSlHIeBwkmty6XtdyKSboVG4KYRF3AMDYEbvPLgPBOx0j4koFQagNBbycDvCgsAeD4H4AfHFckaSuQWSja5zhLmQIobcnA9y9FPJIBGH0uzX4HI2Vsk5ZyfTEvIPyo5Po3l23LA7CFPz%2BmkH%2BbZIF5VQVxOZZLRJqt3KpIqCPSGUB%2BAlBCJlSeqB9U20kBARQxr4ITxwEkHAloz7ainhapCA5bWmpCG60eTRVg8ldeagAvkAA==](url)

**Comment by epasham** [comment]
PR is submitted -> [https://github.com/kyverno/policies/pull/1168](url)
