### ISSUE TITLE
[Discussion] Policy Classification Annotation for Kubernetes version

### ISSUE THREAD

**Issue by thorstenhuhn** [kyverno/policies#117]
Policies using `apiCall` in their `context` might not work with every Kubernetes version, e.g. [unique-ingress-host](https://github.com/kyverno/policies/blob/da1666055a28cd24e40de7e62bcad5f8dd63818f/other/restrict_ingress_host.yaml) policy uses `urlPath` "/apis/networking.k8s.io/v1/ingresses" which is available since Kubernetes 1.19 and will not work for versions before.

A policy classification annotation would help to make this clear explicitly.

**Comment by chipzoller** [comment]
Yep, you're right. We actually discussed this at an earlier contributors meeting and it sounded like the agreement was to add a couple new annotations. One would be to state the tested (implied working) version of Kubernetes and the other for Kyverno. I've created a reminder issue https://github.com/kyverno/policies/issues/130 to track.
