### ISSUE TITLE
policy for blocking ingress if user doesn't specify tls

### ISSUE THREAD

**Issue by saiben10** [kyverno/policies#1193]
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
name: ingress-tls
spec:
validationFailureAction: enforce
background: true
rules:

name: tls
match:
any:
resources:
kinds:
Ingress
operations:
CREATE
UPDATE
validate:
message: "Ingress must have tls config."
pattern:
spec:
tls:

hosts:
"*"
this policy I am trying to use for ingress, i.e. ingress should not be created if we didn't specify tls configuration. But not working
What might be the reason

**Comment by realshuting** [comment]
Please, format your policy properly so that we can copy and paste directly for local testing.

**Comment by saiben10** [comment]
Here i attached the policy as a file.Please let me know if other needed;
Thanks
[ingress-tls.txt](https://github.com/user-attachments/files/17571492/ingress-tls.txt)

**Comment by realshuting** [comment]
@saiben10 - in order to reproduce the issue, we need both **policy** and **resource** manifests, otherwise the result could be altered. PLEASE, provide the two manifests in the proper format.

**Comment by saiben10** [comment]
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    kubernete.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
So the above is my ingress manifest it and in the previous comment i attached my policy manifest. I need to decline this above ingress creation as there is no tls cert mentioned.

**Comment by epasham** [comment]
Can you use the attached policy and confirm if it is working. Note that the policy doesnt allow ingress if tls configuration is missing in the ingress rule

[disallow-ingress-nginx-without-tls.yaml.txt](https://github.com/user-attachments/files/17626510/disallow-ingress-nginx-without-tls.yaml.txt)

**Comment by saiben10** [comment]
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-policy
  namespace: ns-test
spec:
  rules:
    - host: grafana-caasdev03.domain.com
      http:
        paths:
          - backend:
              service:
                name: test-service
                port:
                  number: 80
            path: /
            pathType: Prefix


i am trying to create the above ingress manifest without tls config after applying the above policy mentioned in the previous comment. As I didn't mention the tls config the ingress should not be created but it is creating. Any thing need to change in the policy

**Comment by epasham** [comment]
What is the kubernetes version you are using?

**Comment by saiben10** [comment]
currently using 1.30.5

**Comment by epasham** [comment]
Can you test your policy at the below link. Just append your resource and hit START button to test the policy

https://playground.kyverno.io/#/?content=N4IgDg9gNglgxgTxALhAQzDAagUwE4DOMEAdsgAQDWCAbviRAHTED0NAjADomUwkAmFAMJQArgQAu%2BAArR4CbgFscEtPzSrk3cuRJplFfjAJooUCAHcAtHwDmeHAQJWStvgA8rFmBIAWEUQkrCSgCbXI0EgZVCWISAi0SHR1IWDgYR0ZqOjwGZggWWJCcCgBBM0tyADkAcQBJKoANcjrXBydybz9yABUAGQBlcj5yIQBRPvIcdzB2olICHXCUuXTM7PomVjgNHFsIPAQKAZw4UTwfBAAaavqmlrbHRZHxyeXyVPgMgizaTfyWAQcDlLhRfDBbL53p81j8NrktgUCKIAEYAK1OEgorXsT2hq2%2BvxyeVYij4OXmZHInBA7EY7DpAAYae94SSCmyIFYKXEKDS6QzGMyQKy/giAZRUfQVI5ufhKXzaYwAEwANisdOVAHYWUlkjDCZyAfxHHALmBYqQKAA%2BKzvHQ9cGLGEIYaLcQ4fjkCQQcgo8xwSje3w4YaPDrtAJ4OChs04DRxYYAM2Dof6QyBElirkW9oiDl0EAk5BNSb4nrDqbDuKcLjcJHc5DgpDLtnOCdIjG4BDAp0SOhophg6ktJAAYmgYGIHKU4KOyqIjBJwnhRFBHP3klZdPoSk2Q4GrGANL4wnrkuRFBo4L5NxedJEjnmdNvI%2BcYwln/feAJP%2Bf7xe24kCoFgHD%2BthZAAHD8rAcCwOJzF%2BF4QL2eAdvEd4AVuowAEpjKUPRjEh2EAKrSAAIgRRH/gOQ4jiUX4xlAmEAdMsxPHEf5Yfe25sXMvLkLaxEAb4aAEAAFBA6KYowPanIwIQEAAlOQABkqnUjR3HJFJGJzrJvZwIwAD8imMAcWCmKIODiQA2gAukpjCmFA4mKTcZnGUCcYSFUu7mXglliDZLIgCpACEAC81IimFwnJMoThoLYe40ghTzkDha6hl0/iBL0gxuoWxYuZYnossulVLCQIBXCAb7RjgKDoJguCEAJwESKBeDgVBMEFBw3A/oIDw1meyiqCOaCbnoBiXnwMBXlANjhmeD5REW6FcckrgeMwq1ZFKuQyv1LAOBYFxSMEaB4ClWLkCw3aGZudhzCIYkEH5c27Q2VjTPoYDriu2XbduvhZmALEfCe22AdDfgUIUjgSMefhfqjvg9AgvYUNIDhlu4X4omggY4AIUMXkCeA0PADFaQBs17lIkjxZAeBYvFOgkKIigovgFCQcyJBWCL3AYNg8odSBYF2H1AKDTwfAjelThKCoagaNN4SMxQil/e4APritY1PX24SKZuYMQJIsPYeDKPOP9iiAzgjBJhATDNoo7zeQ4vm7rryO%2ByowShMD66g%2BQ/iSGCEOOwbzvrm7HuMF77z25DeYY7bL7w7eD3oyeWM4%2BQeM4ATRMk5QZOCMRVM0zGFP3jr5D17TXD0/ebMc53DM83zeAC4ytUgNA/A4Y4UYxs1I9nJIECKBPBBTzg5Hlwto4EDPdVwGIkj4EvK9b6gI/TDGFqcTPAC%2BQA

**Comment by saiben10** [comment]
surprised, it is working here not working in my cluster copy and pasted the above manifests any idea on this.
currently i have 3 policies excluding this in my cluster.
1)namespace owner label policy
2) external ips
3) replica limits
will these cause any issue?

**Comment by epasham** [comment]
There shouldn't be an issue with other policies. The policy discussed in this thread works on only ingress objects.
what is the kyverno version in your environment

**Comment by saiben10** [comment]
Version - 3.2.7 i installed

**Comment by saiben10** [comment]
Hy @epasham,
any update on this, waiting for it.
Thanks

**Comment by epasham** [comment]
The attached policy [disallow-ingress-nginx-without-tls.yaml.txt](https://github.com/user-attachments/files/17626510/disallow-ingress-nginx-without-tls.yaml.txt) should work. can you check it and verify again

**Comment by saiben10** [comment]
Ingress Manifest

<img width="668" alt="ing" src="https://github.com/user-attachments/assets/83fba003-f555-4134-ba30-35149ab35b20">

Kyverno Version Screenshot

<img width="675" alt="kyverno-version" src="https://github.com/user-attachments/assets/93fa669a-c0e7-4b25-ae4c-66feccf3e3f7">

Policy Manifest

<img width="724" alt="tls-policy" src="https://github.com/user-attachments/assets/f2ddc8f7-8e64-4b27-aaaa-60087d41a291">



Here I have added an ingress without tls but it is still created even after applying the above yaml(applied the above policy manifest) Attached the screenshots all.
What might be the issue?

**Comment by epasham** [comment]
You should enforce the policy using the below parameter
validationFailureAction: Enforce

**Comment by saiben10** [comment]
Even though i changed to enforce still ingress is creating without tls

**Comment by epasham** [comment]
I just tested the policy against the attached ingress manifest that you shared. The test was successful.

<img width="653" alt="image" src="https://github.com/user-attachments/assets/f0e2d840-e22d-42da-95e5-585e8167b4ad">

**Comment by saiben10** [comment]
So, What might be the issue with mine? Any idea on this

**Comment by epasham** [comment]
you can also test and verify your ingress resource at the following link -> https://killercoda.com/kyverno/scenario/intro

**Comment by saiben10** [comment]
<img width="403" alt="image" src="https://github.com/user-attachments/assets/0306bdee-8d50-432a-b735-e7ebc7748cfc">

Here also same issue it is creating even the policy is applied i used the same files which we used before @epasham could you please check on this

**Comment by epasham** [comment]
can you attach policy and ingress manifest files

**Comment by saiben10** [comment]
[disallow-ingress-nginx-without-tls.yaml (2).txt](https://github.com/user-attachments/files/17700733/disallow-ingress-nginx-without-tls.yaml.2.txt)
[ing-manifest (1).txt](https://github.com/user-attachments/files/17700736/ing-manifest.1.txt)

**Comment by epasham** [comment]
You need to update **validationFailureAction: Enforce** and test the policy. It should work.

**Comment by saiben10** [comment]
oh, it is working fine https://killercoda.com/kyverno/scenario/intro here what might be the wrong in my case.

**Comment by saiben10** [comment]
sorry @epasham it is working fine in all other namespaces except in one namespace ns-test. The same namespace is not working for other polies(namespace owner label,externalIPs,replica limits. kyverno is installed in that namespace.). How to change it to apply the policies for all namespaces.

**Comment by epasham** [comment]
separate kyverno deployment into kyverno namespace. Your problem should be resolved.

**Comment by saiben10** [comment]
okay, Thanks much

**Comment by realshuting** [comment]
Thanks @epasham for helping out! 

@saiben10 - can we close the issue?

**Comment by epasham** [comment]
Yes, this issue can be closed
