### ISSUE TITLE
Restrict Image Registries

### ISSUE THREAD

**Issue by anuragjain08** [kyverno/policies#1196]
I am trying to create this policy with my own image registries and I want to implement it for all kinds i.e. but it is not working for kind - Job.

So can this policy be implemented only for pods as the same registries are going for pods but not for Job. 

             - Deployment
            - CronJob
            - Job
            - ReplicaSet
            - DaemonSet
            - Pod

My Policy Looks like below :

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
  annotations:
    policies.kyverno.io/title: Restrict Image Registries
    policies.kyverno.io/category: Best Practices, EKS Best Practices
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Images from unknown, public registries can be of dubious quality and may not be
      scanned and secured, representing a high degree of risk. Requiring use of known, approved
      registries helps reduce threat exposure by ensuring image pulls only come from them. This
      policy validates that container images only originate from the private ecr registry.     
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: validate-registries
    match:
      any:
      - resources:
          kinds:
            - Deployment
            - CronJob
            - Job
            - ReplicaSet
            - DaemonSet
            - Pod
    validate:
      message: "Unknown image registry."
      pattern:
        spec:
          =(ephemeralContainers):
          - image: "aaaaaaa.dkr.ecr.us-east-1.amazonaws.com/* | bbbbbb.dkr.ecr.ap-south-1.amazonaws.com/* | cccc.dkr.ecr.us-east-1.amazonaws.com/* | ddddd.dkr.ecr.us-east-1.amazonaws.com/*"
          =(initContainers):
          - image: "aaaaaaa.dkr.ecr.us-east-1.amazonaws.com/* | bbbbbb.dkr.ecr.ap-south-1.amazonaws.com/* | cccc.dkr.ecr.us-east-1.amazonaws.com/* | ddddd.dkr.ecr.us-east-1.amazonaws.com/* | cccc.dkr.ecr.us-east-1.amazonaws.com/* | ddddd.dkr.ecr.us-east-1.amazonaws.com/*"
          containers:
          - image: "aaaaaaa.dkr.ecr.us-east-1.amazonaws.com/* | bbbbbb.dkr.ecr.ap-south-1.amazonaws.com/* | cccc.dkr.ecr.us-east-1.amazonaws.com/* | ddddd.dkr.ecr.us-east-1.amazonaws.com/*"

**Comment by epasham** [comment]
The policy should work for jobs as well as job internally creates a pod. Can you provide the job manifest file in proper format to test and validate

**Comment by anuragjain08** [comment]
@epasham thanks for your response.
could it be because of this line - policies.kyverno.io/subject: Pod

**Comment by epasham** [comment]
you should provide the job manifest file in proper format to test and validate

**Comment by epasham** [comment]
I have tested the policy the following policy https://github.com/kyverno/policies/blob/main/best-practices-cel/restrict-image-registries/restrict-image-registries.yaml

Make sure the policy is enforced using the below parameter. Attached screenshot below shows that it works job resource too
validationFailureAction: Enforce 

<img width="653" alt="image" src="https://github.com/user-attachments/assets/626e11f6-4bdc-4228-afd2-e8fe9bcbe559">

**Comment by anuragjain08** [comment]
@epasham thank you for the clarification this policy worked for me even with the below parameter 
validationFailureAction: audit

The only issue in the above policy which I shared  was, I had to remove all the kinds apart from just Pod . And it worked for Job as well. As Job also runs pod internally as you mentioned.

**Comment by epasham** [comment]
Yes, Just use the policy as it is. It should work

**Comment by realshuting** [comment]
Thanks @epasham for helping with the issue.

@anuragjain08 - are we good to close it?

**Comment by anuragjain08** [comment]
Yes , we can close this issue, thanks @epasham 
@realshuting
