### ISSUE TITLE
Sync Secrets

### ISSUE THREAD

**Issue by jsd2150** [kyverno/policies#1202]
There is an error in this policy

generate:
      apiVersion: v1
      kind: Secret
      name: regcred
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        namespace: default
        name: regcred

needs to be
generate:
      apiVersion: v1
      kind: Secret
      name: regcred
      namespace: "{{request.object.metadata.**namespace}**}"
      synchronize: true
      clone:
        namespace: default
        name: regcred

**Comment by epasham** [comment]
This sync-secrets policy will copy the Secret called regcred from default Namespace to new Namespaces when they are created.
The clone parameters are used to specify from which namespace the secret should be cloned and the name of the secret. Let me know if you face any problem

**Comment by realshuting** [comment]
Which policy has this issue?

**Comment by epasham** [comment]
@realshuting: There is no issue with the sync-policy. Looks like @jsd2150 had a clarification. provided details on how to test the policy. asked him to comeback if he faces any problem

**Comment by realshuting** [comment]
> @realshuting: There is no issue with the sync-policy. Looks like @jsd2150 had a clarification. provided details on how to test the policy. asked him to comeback if he faces any problem

I'm closing the issue for now. Please re-open with more details.
