### ISSUE TITLE
[BUG] Drop CAP_NET_RAW is broken

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#161]
Reported on [Slack](https://kubernetes.slack.com/archives/CLGR9BJU9/p1635871845262100). The policy doesn't flatten the `drop` array as it should.

**Comment by mathildeHermet** [comment]
Also the case    
```
drop:
- all
```
will result in the pods beeing blocked while it should pass.

**Comment by chipzoller** [comment]
Since `ALL` is inclusive of `CAP_NET_RAW`, these two policies ([here's the one to drop ALL](https://kyverno.io/policies/best-practices/require_drop_all/require_drop_all/)), are mutually exclusive. The idea is to pick the one that best suits you.
