### ISSUE TITLE
Check deprecated APIs

### ISSUE THREAD

**Issue by ziansong** [kyverno/policies#179]
wo apply cluster policy    
- name: validate-custom-removals
    match:
      resources:
        kinds:
        # - networking.istio.io/v1alpha3/VirtualService
        - autoscaling/v2beta1/HorizontalPodAutoscaler
        - networking.istio.io/v1alpha3/Gateway
  but   autoscaling/v2beta2/HorizontalPodAutoscaler  also deny ,why ???

**Comment by ziansong** [comment]
also if config  networking.istio.io/v1alpha3/VirtualService ,then v1alpha3 and v1beta1 all deny 
if config networking.istio.io/v1beta1/VirtualService  then vibeta1 deny ,  v1alpha3 allow

**Comment by ziansong** [comment]
I found that I actually deployed v2beta2 on the eks cluster, but request.object.kind is really v2beta1

**Comment by realshuting** [comment]
@ziansong - if the policy isn't working as expected, please open an issue in kyverno/kyverno repo with reproduce steps. Thanks!
