### ISSUE TITLE
Test `kyverno/policies:main` against the `kyverno/kyverno:main` CLI

### ISSUE THREAD

**Issue by zeborg** [kyverno/policies#242]
**Describe the bug**
Currently the PRs made against `main` branch of this repo are being tested/checked against the latest [release](https://api.github.com/repos/kyverno/kyverno/releases/latest) CLI build of [kyverno/kyverno](https://github.com/kyverno/kyverno) in the CI workflow. This results in some of the PR checks on this repo getting failed due to some bug fixes/changes that have been introduced to `kyverno/kyverno:main` but haven't been implemented in the latest `release` build.

**Expected behavior**
The `main` branch of this repo should be checked against the `main` branch of [kyverno/kyverno](https://github.com/kyverno/kyverno) in the CI workflow.

**Additional context**
The following PRs have failing build checks due to this issue: https://github.com/kyverno/policies/pull/237 https://github.com/kyverno/policies/pull/241

**Comment by chipzoller** [comment]
Working on building this out now and have an error: https://github.com/chipzoller/kyverno-pss/runs/4983235953?check_suite_focus=true

**Comment by chipzoller** [comment]
Link to https://github.com/kyverno/kyverno/discussions/3049
