### ISSUE TITLE
[Bug] Pod security policy issues

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#272]
### Kyverno Version

1.6.x

### Kubernetes Version

1.20.x

### Kubernetes Platform

Minikube

### Description

I installed the pod security policies and ran a test container. It shows violations which are incorrect.

### Steps to reproduce

See below:

```sh

❯ kustomize build https://github.com/kyverno/policies/pod-security/enforce | kubectl apply -f -
clusterpolicy.kyverno.io/disallow-capabilities configured
clusterpolicy.kyverno.io/disallow-capabilities-strict configured
clusterpolicy.kyverno.io/disallow-host-namespaces configured
clusterpolicy.kyverno.io/disallow-host-path configured
clusterpolicy.kyverno.io/disallow-host-ports configured
clusterpolicy.kyverno.io/disallow-host-process configured
clusterpolicy.kyverno.io/disallow-privilege-escalation configured
clusterpolicy.kyverno.io/disallow-privileged-containers configured
clusterpolicy.kyverno.io/disallow-proc-mount configured
clusterpolicy.kyverno.io/disallow-selinux configured
clusterpolicy.kyverno.io/require-run-as-non-root-user configured
clusterpolicy.kyverno.io/require-run-as-nonroot configured
clusterpolicy.kyverno.io/restrict-apparmor-profiles configured
clusterpolicy.kyverno.io/restrict-seccomp configured
clusterpolicy.kyverno.io/restrict-seccomp-strict configured
clusterpolicy.kyverno.io/restrict-sysctls configured
clusterpolicy.kyverno.io/restrict-volume-types configured

❯ kubectl get cpol
NAME                             BACKGROUND   ACTION    READY
disallow-capabilities            true         enforce   true
disallow-capabilities-strict     true         enforce   true
disallow-host-namespaces         true         enforce   true
disallow-host-path               true         enforce   true
disallow-host-ports              true         enforce   true
disallow-host-process            true         enforce   true
disallow-privilege-escalation    true         enforce   true
disallow-privileged-containers   true         enforce   true
disallow-proc-mount              true         enforce   true
disallow-selinux                 true         enforce   true
require-run-as-non-root-user     true         enforce   true
require-run-as-nonroot           true         enforce   true
restrict-apparmor-profiles       true         enforce   true
restrict-seccomp                 true         enforce   true
restrict-seccomp-strict          true         enforce   true
restrict-sysctls                 true         enforce   true
restrict-volume-types            true         enforce   true

❯ kubectl run nginx --image=nginx
Error from server: admission webhook "validate.kyverno.svc-fail" denied the request:

resource Pod/default/nginx was blocked due to the following policies

disallow-capabilities-strict:
  require-drop-all: 'validation failure: Containers must drop `ALL` capabilities.'
disallow-privilege-escalation:
  privilege-escalation: 'validation error: Privilege escalation is disallowed. The
    fields spec.containers[*].securityContext.allowPrivilegeEscalation, spec.initContainers[*].securityContext.allowPrivilegeEscalation,
    and spec.ephemeralContainers[*].securityContext.allowPrivilegeEscalation must
    be set to `false`. Rule privilege-escalation failed at path /spec/containers/0/securityContext/'
require-run-as-nonroot:
  run-as-non-root: 'validation error: Running as root is not allowed. Either the field
    spec.securityContext.runAsNonRoot must be set to `true`, or the fields spec.containers[*].securityContext.runAsNonRoot,
    spec.initContainers[*].securityContext.runAsNonRoot, and spec.ephemeralContainers[*].securityContext.runAsNonRoot
    must be set to `true`. Rule run-as-non-root[0] failed at path /spec/securityContext/runAsNonRoot/.
    Rule run-as-non-root[1] failed at path /spec/containers/0/securityContext/.'
restrict-seccomp-strict:
  check-seccomp-strict: 'validation error: Use of custom Seccomp profiles is disallowed.
    The fields spec.securityContext.seccompProfile.type, spec.containers[*].securityContext.seccompProfile.type,
    spec.initContainers[*].securityContext.seccompProfile.type, and spec.ephemeralContainers[*].securityContext.seccompProfile.type
    must be set to `RuntimeDefault` or `Localhost`. Rule check-seccomp-strict[0] failed
    at path /spec/securityContext/seccompProfile/. Rule check-seccomp-strict[1] failed
    at path /spec/containers/0/securityContext/.'

```

### Expected behavior

Only the ` run-as-non-root` violation should be shown.

The others are invalid as the pod is not setting `allowPrivilegeEscalation` and ` spec.securityContext.seccompProfile.type`.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Jim, based on how the controls are stated for the restricted profile (and therefore how the policies are written), this all looks like correct behavior. There are four rules reporting violations (policy/rule is the format):

1. [disallow-capabilities-strict/require-drop-all](https://github.com/kyverno/policies/blob/main/pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict.yaml)
2. [disallow-privilege-escalation/privilege-escalation](https://github.com/kyverno/policies/blob/main/pod-security/restricted/disallow-privilege-escalation/disallow-privilege-escalation.yaml)
3. [require-run-as-nonroot/run-as-non-root](https://github.com/kyverno/policies/blob/main/pod-security/restricted/require-run-as-nonroot/require-run-as-nonroot.yaml)
4. [restrict-seccomp-strict/check-seccomp-strict](https://github.com/kyverno/policies/blob/main/pod-security/restricted/restrict-seccomp-strict/restrict-seccomp-strict.yaml)

This is the Pod template which results from that `kubectl run` command:

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
```

For reference, here's the [link ](https://kubernetes.io/docs/concepts/security/pod-security-standards/) to the upstream Pod Security Standards docs which outline how the control should function. And this is why each policy/rule combination is showing a violation:

1. The `nginx` container does not explicitly specify `ALL` in its `securityContext.capabilities.drop[]` array. The control doesn't list this as optional; it is required to be set. It's not present.
2. The `nginx` container does not explicitly set `securityContext.allowPrivilegeEscalation` to `false`. It's not present.
3. Either the `nginx` container or the Pod as a whole must set `securityContext.runAsNonRoot` to `true`. Neither of these is the case.
4. Similar to three above. `securityContext.seccompProfile.type` must explicitly specify either `RuntimeDefault ` or `Localhost`. This is also absent.

**Comment by JimBugwadia** [comment]
Got it! Had missed those details in the PSS changes. Thanks for clarifying, @chipzoller!
