### ISSUE TITLE
[Sample] prevent node proxy access

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#280]
### Problem Statement

See: https://blog.aquasec.com/privilege-escalation-kubernetes-rbac

Using a node proxy role, it possible to by pass the API server

### Solution Description

Prevent configuration of a node proxy role

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
Nodes/proxy is a subresource so writing this might be impacted by the same issues with subresources mentioned on the call today.

**Comment by chipzoller** [comment]
This has been completed and is available [here](https://main.kyverno.io/policies/other/restrict-clusterrole-nodesproxy/restrict-clusterrole-nodesproxy/).
