### ISSUE TITLE
[Bug] Url in README not found

### ISSUE THREAD

**Issue by dadav** [kyverno/policies#292]
The URL [in the readme](https://github.com/kyverno/policies/blob/main/README.md?plain=1#L24) is not working: [https://github.com/kyverno/policies/tree/main/pod-security/baseline/disallow-adding-capabilities](https://github.com/kyverno/policies/tree/main/pod-security/baseline/disallow-adding-capabilities)

**Comment by chipzoller** [comment]
Thanks for the report. I'll fix this. In the mean time, the example path is here: https://github.com/kyverno/policies/tree/main/pod-security/baseline/disallow-capabilities

**Comment by chipzoller** [comment]
Closed in #314
