### ISSUE TITLE
Kyverno Expects a namespace "foo" 

### ISSUE THREAD

**Issue by kranurag7** [kyverno/policies#320]
- While testing the policies with `kyverno test disallow_latest_tag` everything is okay but when I want to create the resources in order to see the policies in action, the policy is expecting to have a namespace "foo". I think we should remove the `namespace: foo` from the policy, so that it doesn't throw any error. 
![Screenshot from 2022-05-09 08-13-55](https://user-images.githubusercontent.com/81210977/167332399-cababd44-b52c-41c1-814c-4b824b701a45.png)

**Comment by kranurag7** [comment]
@chipzoller Should I work on this and raise a PR?

**Comment by chipzoller** [comment]
Thanks, fixed in my local fork. Will include this in an upcoming PR.

**Comment by kranurag7** [comment]
Thank you, @chipzoller, Is there any policy on which I can work? I want to start with writing policies.

**Comment by chipzoller** [comment]
What is it you'd like to do exactly? In this case, there was no work necessary on the policy but rather a few of the test resources. If you haven't done so already, I'd highly recommend getting familiar with the [documentation](https://kyverno.io) and then perusing some of the many [sample policies](https://kyverno.io/policies) to see how they're written and what they do. Lastly, come join us on #kyverno in Kubernetes Slack and ask questions and receive help.

**Comment by kranurag7** [comment]
Thank you, @chipzoller, I will follow up the further discussions in slack.

**Comment by chipzoller** [comment]
Closed in #334
