### ISSUE TITLE
[Clean-up] In `main` remove variables and references thereto for `request.operation` equals `CREATE`

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#338]
As of the 1.7.0 CLI, if `request.operation` is not specified in a values file, it will be defaulted to `CREATE`. This results in reduced complexity when writing test cases as there is no longer a need for a values file which defines on the `request.operation` variable. Clean these up.

**Comment by chipzoller** [comment]
@viveksahu26 since your work resulted in this efficiency, this would be a nice bit of clean-up for kyverno/policies if you wanted to take it on.

**Comment by viveksahu26** [comment]
Sure, /assign me.

**Comment by viveksahu26** [comment]
Removing `values.yaml` file which only contains variables, `request.operation=CREATE`. And what if `values.yaml` file contains multiple varibles including `request.operation=CREATE`. So, will it be good choice of removing only those variables from `values.yaml` which are pointing to `request.operation=CREATE`

**Comment by chipzoller** [comment]
My suggestion would be to only remove values and variables which solely exist to specify CREATE operations.

**Comment by viveksahu26** [comment]
ok, got it.

**Comment by viveksahu26** [comment]
Hey @chipzoller , do we need to update similarly for website policies?

**Comment by chipzoller** [comment]
What do you mean by "website policies"?

**Comment by viveksahu26** [comment]
Btw I was talking about these [policies](https://kyverno.io/policies/). But it's fine, no need to do any changes because  there are only bunch of policies not values file.
