### ISSUE TITLE
[Sample] Disallow serviceAccount duplicate

### ISSUE THREAD

**Issue by developer-guy** [kyverno/policies#340]
### Problem Statement

Some of the services, such as Workload identity providers of cloud services, SPIFFE, etc., use service accounts and namespaces to give an identity to a pod, so we might want service accounts to be unique for pods. We (w/@dentrax) opened this issue to further discuss this topic, if you agree on this idea, we're willing to write a policy for this, thanks in advance. with

### Solution Description

Use context variable to store service account names by querying api-server to get all the service accounts within the same namespace for the pod, then use this information to decide whether it should be allowed.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
So is the policy here to prevent duplicate ServiceAccounts from being _created_? If so, the API server will perform that check already. You cannot have two ServiceAccounts with the same name in the Namespace.

```$ k create sa foo
serviceaccount/foo created

$ k create sa foo
error: failed to create serviceaccount: serviceaccounts "foo" already exists
```

**Comment by chipzoller** [comment]
How would you handle multiple replicas from the same Pod controller? They're all going to have to use the same SA.

**Comment by JimBugwadia** [comment]
An option is to bind a service account to an image. The binding can be managed in a ConfigMap, which feeds the policy.

**Comment by JimBugwadia** [comment]
A variation would be to create the binding on first use, applying the Trust On First Use (TOFU) principal (thanks Dan!) 

So, when a SA is assigned, mutate a CM and add the entry to bind to an image. Then not let any other image use the same SA.

**Comment by chipzoller** [comment]
@developer-guy based on what was previously said, is there action for you here? If not, shall we close this?

**Comment by chipzoller** [comment]
Closing.
