### ISSUE TITLE
[Sample] [Karpenter] inject `do-not-evict` for batch workloads

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#351]
### Problem Statement

https://kubernetes.slack.com/archives/C02SFFZSA2K/p1657301386740659?thread_ts=1657299639.195769&cid=C02SFFZSA2K

> Some users may be interested in automatically applying the karpenter.sh/do-not-evict: true annotation to pods owned by Jobs/CronJobs.  I think this may become more important when cluster consolidation is implemented.

### Solution Description

Based on Kind, inject the `karpenter.sh/do-not-evict: true` annotation to pod templates

### Slack discussion

https://kubernetes.slack.com/archives/C02SFFZSA2K/p1657301386740659?thread_ts=1657299639.195769&cid=C02SFFZSA2K

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
Would this be injected to the Pod template for Jobs and CronJobs, or would this just be injected into Pods directly if the `ownerReferences.kind` is a `Job`?

**Comment by chipzoller** [comment]
@JimBugwadia I have an open PR and can fit this in if the above is correct.

**Comment by JimBugwadia** [comment]
Nice, thanks! I prefer annotating the template, although both should work.

**Comment by chipzoller** [comment]
The Pod template is what is being annotated here, or did you mean the top level controller?

**Comment by JimBugwadia** [comment]
Yes, the pod template.

**Comment by chipzoller** [comment]
Closed in #352
