### ISSUE TITLE
[Bug] inconsistent boolean quoting in sample policies

### ISSUE THREAD

**Issue by zswanson** [kyverno/policies#361]
### Kyverno Version

1.7.x

### Kubernetes Version

1.22.x

### Kubernetes Platform

GKE

### Description

Several sample policies in the repo are using quotes around booleans in `spec.validation.pattern` while others treat the value as an actual boolean. These are inconsistent and should use the same standard across the policy library. 

Example using quoted bools: https://kyverno.io/policies/pod-security/baseline/disallow-host-namespaces/disallow-host-namespaces/

Example using regular bools: https://kyverno.io/policies/pod-security/restricted/require-run-as-nonroot/require-run-as-nonroot/

### Steps to reproduce

n/a 

### Expected behavior

Consistent use of quoting (or no quotes) in policy samples when booleans are used.

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1658237801940049

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
The rationale was internal consistency at a time when quoting of booleans was required in policies using overlay patterns. If that is no longer required, and I believe it isn't, we can update the policies (consistently) to remove quotes. However, as you've no doubt seen, it doesn't affect the efficacy of the policies.
