### ISSUE TITLE
Mutate label to the existing resource 

### ISSUE THREAD

**Issue by vgokul984** [kyverno/policies#369]
### Kyverno Version

1.7.x

### Kubernetes Version

1.20.x

### Kubernetes Platform

EKS

### Description

I am trying to add a label to the existing namespaces with label app: value. It adds the label but not the correct value name. similar I am trying to make the deployment replicas count to 1 for all the namespaces in the cluster by excluding the kube-system namespace, but the policy is not getting excluded for kube-system is getting patched .
[label-existing-namespaces.txt](https://github.com/kyverno/policies/files/9242997/label-existing-namespaces.txt)
![image](https://user-images.githubusercontent.com/39961093/182397060-ccd4f17f-6a53-4d40-8a00-2f2dbecc31cc.png)

### Steps to reproduce

Kubectl apply -f 
[label-existing-namespaces.txt](https://github.com/kyverno/policies/files/9243008/label-existing-namespaces.txt)

### Expected behavior

I would like to add the mutate policy to add the labels to the existing namespace without any mismatch. The deployment replica count needs to be 1 for all the namespaces except some namespaces. example kube-system

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
This really isn't a policy "bug", and as I see you've already created a Slack thread for this [here](https://kubernetes.slack.com/archives/CLGR9BJU9/p1659449357735989), let's close this and continue discussion on Slack.
