### ISSUE TITLE
[Sample] Deny undefined Deployment from executing

### ISSUE THREAD

**Issue by awhitepl** [kyverno/policies#379]
### Problem Statement

Sometimes Deployments are launched in a cluster and forgotten about or are unauthorized. 

### Solution Description

This policy would deny all undefined Deployments from existing in the cluster. 

### Example "Good" Resource

```yaml
Whitelisting Kyverno makes sense.
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
In your Solution Description, I don't understand what you're saying here. Please elaborate.

**Comment by chipzoller** [comment]
Closing until more details are provided.
