### ISSUE TITLE
Add labels to policies

### ISSUE THREAD

**Issue by james-callahan** [kyverno/policies#381]
Currently policies are enriched with metadata via annotatations.
Instead (or in addition), could we add labels to the policies?

 - Would provide a workaround for https://github.com/kubernetes-sigs/kustomize/issues/3887#issuecomment-1229717161
 - Would allow easily show metadata when using `kubectl` via the ` -L, --label-columns=[]` argument. e.g. `kubectl get clusterpolicy -L policies.kyverno.io/category`

**Comment by chipzoller** [comment]
Annotations are quite important right now on Kyverno policies as they're the means by which the whole filtering system works on the [policy webpage](https://kyverno.io/policies/). That plus the rendering program we use to generate Markdown from the policies relies upon it. We'll consider it, but it's not that easy to just switch over.
