### ISSUE TITLE
[Sample] Secret Rotation Alert

### ISSUE THREAD

**Issue by awhitepl** [kyverno/policies#386]
### Problem Statement

Have a policy to fail (or alert via policy-reporter) of secret age after a certain length of time.

### Solution Description

This policy would check that best practices are maintained for secret rotation in a cluster. 

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
Need more details on this request, please.

**Comment by chipzoller** [comment]
@awhitepl

**Comment by awhitepl** [comment]
Sorry, just saw the ping. It is just an idea to add an extra layer of alerting for long lasting secrets that might be unexpected behavior from secret rotation strategies. If secret age > 30 days fail and in audit mode it would send notifications to the correct channel via mechanisms setup in policy-reporter. A more advanced usage would be to use mutate to autogenerate the secret but that has a higher level of complexity than what I am suggesting.

**Comment by chipzoller** [comment]
So would you just expect to look at `metadata.creationTimestamp` for this? What if someone updates the existing Secret? That value wouldn't get updated and there by default isn't anything else written to it.

**Comment by chipzoller** [comment]
@awhitepl

**Comment by chipzoller** [comment]
Closing with no response.
