### ISSUE TITLE
[Bug] Fix 1.8 CLI tests failure

### ISSUE THREAD

**Issue by realshuting** [kyverno/policies#387]
### Kyverno Version

1.8.0-rc1

### Kubernetes Version

1.24.x

### Kubernetes Platform

Bare metal

### Description

Need to fix CLI tests failure against release-1.8 branch https://github.com/kyverno/policies/runs/8248978631?check_suite_focus=true#step:5:122.

### Steps to reproduce

n/a

### Expected behavior

n/a

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Fixed by https://github.com/kyverno/policies/pull/388

**Comment by chipzoller** [comment]
My mistake, reopen.

**Comment by chipzoller** [comment]
Merged
