### ISSUE TITLE
I set background to true, but my rules are not valid for existing resources and must be rebuilt to take effect

### ISSUE THREAD

**Issue by lu-you** [kyverno/policies#399]
### Kyverno Version

1.7.x

### Kubernetes Version

1.20.x

### Kubernetes Platform

Other (specify in description)

### Description

I set background to true, but my rules are not valid for existing resources and must be rebuilt to take effect

k8s cluster version：1.19
rule:
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-dnspolicy
spec:
  background: true
  rules:
  - name: add-dnspolicy
    match:
      all:
      - resources:
          kinds:
          - Deployment
          namespaceSelector:
            matchLabels:
              dnspolicy: customer
    mutate:
      patchStrategicMerge:
        spec:
          template:
            spec:
              dnsPolicy: None
              dnsConfig:
                nameservers:
                - xxxx
                - xxxx
                searches:
                - ns1.svc.cluster.local
                - svc.cluster.local
                - cluster.local
                options:
                - name: ndots
                  value: "1"
                - name: timeout
                  value: "1"

### Steps to reproduce

rule:

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-dnspolicy
spec:
  background: true
  rules:
  - name: add-dnspolicy
    match:
      all:
      - resources:
          kinds:
          - Deployment
          namespaceSelector:
            matchLabels:
              dnspolicy: customer
    mutate:
      patchStrategicMerge:
        spec:
          template:
            spec:
              dnsPolicy: None
              dnsConfig:
                nameservers:
                - xxxx
                - xxxx
                searches:
                - ns1.svc.cluster.local
                - svc.cluster.local
                - cluster.local
                options:
                - name: ndots
                  value: "1"
                - name: timeout
                  value: "1"

### Expected behavior

I expect that it will take effect on the currently existing resources as described in the background

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
@lu-you please see the documentation on mutation for existing resources [here](https://main.kyverno.io/docs/writing-policies/mutate/#mutate-existing-resources). This is not controlled by the `background` flag and so it appears you're under the wrong impression of how this works. Closing this as it's a usage issue, but feel free to respond here or come to the #kyverno channel on Kubernetes Slack if you still need assistance.
