### ISSUE TITLE
[Bug] Kyverno doesn't allow adding labels to pods

### ISSUE THREAD

**Issue by leon-marcel** [kyverno/policies#402]
### Kyverno Version

1.7.x

### Kubernetes Version

1.21.x

### Kubernetes Platform

OpenShift

### Description

Kyverno can't add Labels to pod because it is missing the required rights. 

### Steps to reproduce

1. Install kyverno through Helm package
2. Create a policy that adds a label to pods
3. Kyverno can not update the pods

### Expected behavior

I exptected that kyverno was able to alter the pods

### Screenshots

---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ensure-costmanager-labels-dev
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: ensure-costmanager-labels-dev
    match:
      all:
      - resources:
          namespaces:
          - "nv-schulung-*"
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            +(cost-management-category): application

### Kyverno logs

```shell
update_request_controller.go:322] background/ensure-costmanager-labels-dev "msg"="failed to update target resource" "error"="pods \"kube-controller-manager-operator-77c9b466d8-zvvhq\" is forbidden: User \"system:serviceaccount:kyverno:kyverno\" cannot update resource \"pods\" in API group \"\" in the namespace \"openshift-kube-controller-manager-operator\"" "apiVersion"="v1" "kind"="Pod" "policy"="ensure-costmanager-labels-dev" "name"="kube-controller-manager-operator-77c9b466d8-zvvhq" "namespace"="openshift-kube-controller-manager-operator"
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
@leon-marcel apologies for the delay here. This is one (although there are many) example of users potentially needing to grant the Kyverno ServiceAccount additional privileges needed in some cases. This isn't a "bug"; it's a desire to balance commonly-performed tasks with the need for minimal privileges. This is noted in the docs [here](https://main.kyverno.io/docs/installation/#roles-and-permissions) and [here](https://main.kyverno.io/docs/writing-policies/mutate/#mutate-existing-resources) (the latter being what you're attempting to do with the policy).

I'm closing this issue, but feel free to respond or come talk with us in the #kyverno channel in Kubernetes slack.
