### ISSUE TITLE
The current require-network-policy only checks preexisting NetworkPolicy

### ISSUE THREAD

**Issue by vilaspatel** [kyverno/policies#406]
### Problem Statement

The current require-network-policy only checks preexisting Network Policy for deployment , it skips the existing deployments 

policy : "https://kyverno.io/policies/other/require_netpol/require_netpol/" 

### Solution Description

can we have a policy to check the deployments which were created before kyverno policy was deployed .

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by kranurag7** [comment]
@vilaspatel In the same policy, you can use `background: true`

**Comment by chipzoller** [comment]
Correct, yes, you should configure `background: true`. You may also need to remove the precondition as there is no operation for an existing resource. Closing but feel free to respond.
