### ISSUE TITLE
[Bug] Baseline policies generate PolicyReports rather than ClusterPolicyReports

### ISSUE THREAD

**Issue by alexo1088** [kyverno/policies#456]
### Kyverno Version

1.7.x

### Kubernetes Version

1.23.x

### Kubernetes Platform

EKS

### Description

I'm actually running Kyverno 1.8.1:
kyverno/kyverno-policies         	2.6.1        	v1.8.1
kyverno/kyverno                  	2.6.1        	v1.8.1

Not sure why I can't select that in the drop down.

I'm curious as to why the baseline policies generate policy reports rather than cluster policy reports:

The baseline policies all generate 'policyreports', but a custom cluster policy that I wrote generates a 'clusterpolicyreport'.  All policies are defined as 'ClusterPolicies', so the expected behaviour would be that they all generate the same type of report

### Steps to reproduce

1. Create a custom cluster policy report
2. Ensure background is set to true
3. Query for clusterpolicyreports and compare to policyreports
4. Custom ClusterPolicy reports under 'clusterpolicyreports', but all other baselines appear under 'policyreports'

### Expected behavior

The baseline policies, which are defined as ClusterPolicies, should generate clusterpolicyreports and not policyreports

### Screenshots

```
NAME                             BACKGROUND   VALIDATE ACTION   READY
disallow-capabilities            true         enforce           true
disallow-host-namespaces         true         enforce           true
disallow-host-path               true         enforce           true
disallow-host-ports              true         enforce           true
disallow-host-process            true         enforce           true
disallow-privileged-containers   true         enforce           true
disallow-proc-mount              true         enforce           true
disallow-selinux                 true         enforce           true
require-labels                   true         enforce           true
restrict-apparmor-profiles       true         enforce           true
restrict-seccomp                 true         enforce           true
restrict-sysctls                 true         enforce           true
```

```
╰─$ kubectl get cpolr
NAME                  PASS   FAIL   WARN   ERROR   SKIP   AGE
cpol-require-labels   0      10     0      0       0      21m
```

```
╰─$ kubectl get polr
NAME                                  PASS   FAIL   WARN   ERROR   SKIP   AGE
cpol-disallow-capabilities            2      0      0      0       0      2d
cpol-disallow-host-namespaces         2      0      0      0       0      2d
cpol-disallow-host-path               2      0      0      0       0      2d
cpol-disallow-host-ports              2      0      0      0       0      2d
cpol-disallow-host-process            2      0      0      0       0      2d
cpol-disallow-privileged-containers   2      0      0      0       0      2d
cpol-disallow-proc-mount              2      0      0      0       0      2d
cpol-disallow-selinux                 4      0      0      0       0      2d
cpol-restrict-apparmor-profiles       2      0      0      0       0      2d
cpol-restrict-seccomp                 2      0      0      0       0      2d
cpol-restrict-sysctls                 2      0      0      0       0      2d
```

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
The type of report is not determined by the type of policy but rather by the resource.

https://kyverno.io/docs/policy-reports/

**Comment by alexo1088** [comment]
Thanks!  I realized that after asking within the slack channel.  I'll go ahead and close.
