### ISSUE TITLE
[Sample] add GitOpsCon 2022 policies 

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#458]
### Problem Statement

Add sample policies from:

https://github.com/Avni-Sharma/gitopscon_na_2022_session/tree/main/policies

### Solution Description

Sample policies for ArgoCD, CAPI, Kyverno:

https://github.com/Avni-Sharma/gitopscon_na_2022_session/tree/main/policies

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
@dolisss are you still handling this?

**Comment by chipzoller** [comment]
@dolisss are you still interested in taking this up?
