### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by nikgattu** [kyverno/policies#466]
### Kyverno Version

1.7.x

### Kubernetes Version

1.20.x

### Kubernetes Platform

GKE

### Description

Unable to label Deployment names to a K8 pod

### Steps to reproduce

1.apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-new-labels
  annotations:
    policies.kyverno.io/title: Add Labels
    policies.kyverno.io/category: K8 pods
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Label
    policies.kyverno.io/description: >-
      Labels are used as an important source of metadata describing objects in various ways
      or triggering other functionality. Labels are also a very basic concept and should be
      used throughout Kubernetes. This policy performs a simple mutation which adds the below metadata lables
spec:
  failurePolicy: Ignore
  rules:
  - name: add-new-labels
    match:
      resources:
        kinds:
        - Deployment
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            component: "{{request.object.metadata.name}}"
            deployment_tool: adhoc
            component_owner_dl: honey-sre

### Expected behavior

Need to label the deployment pods

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
You're matching on `Deployments` and not Pods. Only Deployments will be labeled. Also, would just like to inform you that the correct abbreviation for "Kubernetes" is K8s, not "K8".
