### ISSUE TITLE
[Sample]  Need to use Deployment name as Labelling component for kubernetes pod

### ISSUE THREAD

**Issue by nikgattu** [kyverno/policies#467]
### Problem Statement

I want to use  Deployment name as Labelling component for kubernetes pod . 
Below is the requirment we are trying to mutate the policy
can we change the value of the label to reference the deployment resource? for example, the daemonset name datadog instead of the pod instance id datadog-ias31f

### Solution Description

I need a sample policy where we can access the deployment name as Label name for a pod

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
Addressed on Slack

https://kubernetes.slack.com/archives/CLGR9BJU9/p1670393323427489
