### ISSUE TITLE
Add Kyverno policy repo to ArtifactHub

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#491]
Kyverno policies can now be listed and searched on ArtifactHub. See:

https://github.com/artifacthub/hub/issues/2653

We need to register the policy repo with ArtifactHub as detailed here:

https://github.com/artifacthub/hub/issues/2653#issuecomment-1377723000

## Objective

Devise an organizational system, which may involve developing a custom application, and process so that all Kyverno policies in the `main` branch of this kyverno/policies repo are reflected, searchable, and have complete metadata on artifacthub.io. Artifact Hub now has support for Kyverno policies in addition to other policy engines, yet none are currently made available. Kyverno has the largest policy library of any Kubernetes policy engine which grows regularly. The ideal solution and desired outcome of this mentorship is as follows:

1. All present policies are "feature complete" and searchable on artifacthub.io. All possible descriptive metadata is complete and correct to the fullest extent allowed by the present capabilities of Artifact Hub.
2. A system and strategy is devised to allow changes to existing policies and new policies to be listed on artifacthub.io in a way that is as automated as possible.

**Comment by zeus2611** [comment]
Hello @chipzoller  @JimBugwadia this looks pretty interesting and good place to start my open source journey. I would like to contribute to this. And, would be really helpful if you could guide me for same during lfx mentorship '23.  i have experience with Golang,  DevOps Automation(CI/CD, terraform, Ansible etc), GitHub Actions. I don't have any experience with artifact hub. But, i will start looking into this for prep work.

**Comment by chipzoller** [comment]
Thanks for the interest. Please make a formal application to the LFX mentorship program if you're interested in participating.

**Comment by Ashwin901** [comment]
Hello @JimBugwadia @chipzoller, the policies in this repository has been very useful for me to write my own policies for my projects and get a better understanding of kyverno policies. And I have been using ArtifactHub to install various applications on my cluster for quite some time now. This project seems very interesting to me and I am looking forward to contribute to the project.

**Comment by guohaoyu110** [comment]
Hi @JimBugwadia @chipzoller I am CS graduate student from USC. I am very interested in this project and have project experience with go, docker and kubernetes. I just applied to the LFX mentorship program. Could you give some suggestions on getting started on this project? Thank you.

**Comment by chipzoller** [comment]
Thanks for those expressing interest in this mentorship. Please make your application [here](https://mentorship.lfx.linuxfoundation.org/project/f502b839-a804-4a6c-8da5-3985ce25883e) and upload the required materials. We will review all candidates at the close of the application window. Please see the initial post for a more thorough description of the objective of this mentorship.

**Comment by bhavyastar** [comment]
Hey, @JimBugwadia @chipzoller I am CS Undergraduate from India. I am also Junior Developer Evangelist at Merico. I am very much interested in the project and also have knowledge of Go, Docker and Kubernetes. It would be great if I will get some suggestions on getting started on this project. 
Thank you!

**Comment by chipzoller** [comment]
Please see above message.

**Comment by chipzoller** [comment]
Based on some new information from AH maintainers, AH expects Kyverno policies to be named the same as the folder in which they are found. Need to ensure this consistency when adding `artifacthub-pkg.yml` files to all.

**Comment by chipzoller** [comment]
We also have to have all policies in individual folders.

**Comment by chipzoller** [comment]
Need to also make sure annotations get populated: https://artifacthub.io/docs/topics/annotations/kyverno/

**Comment by chipzoller** [comment]
Closed by PRs:

#545 
#547 
#550 
#552 
#554 
#561 
#563 

Thank you to @guohaoyu110 !
