### ISSUE TITLE
Update all policies with modern language

### ISSUE THREAD

**Issue by HaiderAli-everest** [kyverno/policies#492]
### Kyverno Version

1.4.x

### Kubernetes Version

1.20.x

### Kubernetes Platform

EKS

### Description

In some policies match block does not have the any clause under it which is causing the "Rule is matching an empty set" error, while creating the policies.

### Steps to reproduce

1. Add exclude block in any policy which does not have 'any' clause under 'match' block then this will give you an  "Rule is matching an empty set" error. 
2. The policies I tested are validate-probes, disallow-default-namespace, memory-requests-equal-limits, deployment-has-multiple-replicas.
3. apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-probes
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Validate Probes
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.3.6
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Liveness and readiness probes accomplish different goals, and setting both to the same
      is an anti-pattern and often results in app problems in the future. This policy
      checks that liveness and readiness probes are not equal.      
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: validate-probes
      match:
        any:
        - resources:
            kinds:
            - Deployment
            - DaemonSet
            - StatefulSet
      exclude:
        any:
        - resources:
            namespaces:
            - cert-manager
      validate:
        message: "Liveness and readiness probes cannot be the same."
        deny:
          conditions:
            any:
            - key: "{{ request.object.spec.template.spec.containers[?readinessProbe==livenessProbe] | length(@) }}"
              operator: GreaterThan
              value: "0"
      

### Expected behavior

I expected it to run when I added an exclude  block

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Policies also need to be refreshed in these additional ways:

* `any` / `all` under `deny.conditions`
* Remove use of deprecated operators `In` and `NotIn`
