### ISSUE TITLE
[Bug] need help to define cluster policy 

### ISSUE THREAD

**Issue by gabo89** [kyverno/policies#502]
### Kyverno Version

1.4.x

### Description

im having trouble writing a cluster policy to block deployment of app in kubernestes that have security issues in their images

following this guide  everything work as expected , i checked the cosign spec and trying to make the filter for my solution  but im unable to define it properly on the yaml  , i tried to following below, 

### **enforce policy to allow images that doesnt have any security vulnerabilites base on trivy report** 
example template 
https://github.com/kyverno/policies/blob/main/best-practices/disallow-empty-ingress-host/disallow_empty_ingress_host.yaml

what is 

```
`[]`  is like convert the last ouput into array? 
| length(@) not sure what is this? i think is count letter in a string
| length is like count the object in array i believe
```

```apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-number-vulnerabilities
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 10
  failurePolicy: Fail
  rules:
    - name: without-having-security-stuff
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "<your_image>"
        attestors:
        - entries:
          - keyless:
              subject: "<url>"
              issuer: "<url>"
        attestations:
        - predicateType: cosign.sigstore.dev/attestation/vuln/v1
          conditions:
          - all:
            - key: "{{ scanner.result.Results[0].Vulnerabilities[]) || `[]` | length }}"
              operator: LessThanOrEquals
              value: "0"
```

https://neonmirrors.net/post/2022-07/attesting-image-scans-kyverno/
https://github.com/sigstore/cosign/blob/main/specs/COSIGN_VULN_ATTESTATION_SPEC.md

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
@gabo89 please describe what you wish to accomplish here.

**Comment by gabo89** [comment]
hello, i want to allow all deployment in kubernetes where the image  vulnerabilites issues detected by trivyis zero, the trivy analisys is done in another process , i already have the process of image analysis on the pipeline CI but also planing to implement it as policy, im trying to count the number vulnerabilities in the yaml from "cosign.sigstore.dev/attestation/vuln/v1" without success via this filter scanner.result.Results[0].Vulnerabilities[]

**Comment by chipzoller** [comment]
Can you please show the attested predicate here?

**Comment by gabo89** [comment]
im only following this guide to guess the spec https://github.com/sigstore/cosign/blob/main/specs/COSIGN_VULN_ATTESTATION_SPEC.md
 , is it posible to retrive the real spec data?

**Comment by chipzoller** [comment]
You need to first have an image with an attested scan attached to the image. Do you have that already or not?

**Comment by gabo89** [comment]
yes i following this guide https://neonmirrors.net/post/2022-07/attesting-image-scans-kyverno/ , i use this command 
cosign attest --replace --predicate scan.json --type vuln ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }

im checking about how to get the  cosign verify-attestation passing the predicate  ,https://github.com/sigstore/cosign/blob/main/doc/cosign_verify-attestation.md

**Comment by chipzoller** [comment]
If you followed my article then you will be able to return the attested predicate like so:

```sh
$ COSIGN_EXPERIMENTAL=1 cosign verify-attestation --type vuln ghcr.io/chipzoller/zulu:v0.0.15 | jq .payload -r | base64 --decode | jq

Verification for ghcr.io/chipzoller/zulu:v0.0.15 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - Any certificates were verified against the Fulcio roots.
Certificate subject:  https://github.com/chipzoller/zulu/.github/workflows/vulnerability-scan.yaml@refs/heads/main
Certificate issuer URL:  https://token.actions.githubusercontent.com
GitHub Workflow Trigger: schedule
GitHub Workflow SHA: a5091aa239b86fbdda3c7a047ff858ce672723ab
GitHub Workflow Name: vulnerability-scan
GitHub Workflow Trigger chipzoller/zulu
GitHub Workflow Ref: refs/heads/main
{
  "_type": "https://in-toto.io/Statement/v0.1",
  "predicateType": "cosign.sigstore.dev/attestation/vuln/v1",
  "subject": [
    {
      "name": "ghcr.io/chipzoller/zulu",
      "digest": {
        "sha256": "4861c443071a1ba62d11f0ab60fba4d3edd742802a09794ef9314ce0b21b2608"
      }
    }
  ],
  "predicate": {
    "invocation": {
      "parameters": null,
      "uri": "",
      "event_id": "",
      "builder.id": ""
    },
    "scanner": {
      "uri": "pkg:github/aquasecurity/trivy@0.34.0",
<snip>
```

**Comment by gabo89** [comment]
thanks you for the babysit, i managed to find the error , you can close the ticket !
