### ISSUE TITLE
Prepend Image Registry: initcontainers rule uses name instead of path for the image path

### ISSUE THREAD

**Issue by michael-barker** [kyverno/policies#509]
In the [prepend-registry policy](https://kyverno.io/policies/other/prepend_image_registry/prepend_image_registry/), the `prepend-registry-initcontainers` rule has a bug where the name is of the image is specified where this should be the path.

Currently the image is set to the follow.
```
image: registry.io/{{ images.initContainers."{{element.name}}".name}}:{{images.initContainers."{{element.name}}".tag}}
```

This should be.
```
image: registry.io/{{ images.initContainers."{{element.name}}".path}}:{{images.initContainers."{{element.name}}".tag}}
```

**Comment by chipzoller** [comment]
Thank you for the report. Would you be interested in submitting a PR for this minor fix?

**Comment by michael-barker** [comment]
@chipzoller Working on one now :grin:

**Comment by michael-barker** [comment]
Another thing that I've noticed with this policy, if you submit an image that uses a digest then the image format becomes invalid. I haven't worked with Kyverno enough to be able to implement.
