### ISSUE TITLE
Restrict node selection: every Pod gets a .spec.nodeName, every Pod triggers a policy error

### ISSUE THREAD

**Issue by remram44** [kyverno/policies#525]
This field exists on every Pod once they are scheduled. This Policy will create audit warnings 100% of the time.

**Comment by chipzoller** [comment]
Add a precondition that only triggers on CREATE. That should fix it.

**Comment by fadecore** [comment]
As I had/have the same issue https://github.com/kyverno/policies/issues/512 , ca we open an MR?

**Comment by chipzoller** [comment]
Yes, please open a PR.
