### ISSUE TITLE
restrict-node-selection not working

### ISSUE THREAD

**Issue by curiousperson101** [kyverno/policies#532]
### Kyverno Version

1.4.x

### Kubernetes Version

1.20.x

### Kubernetes Platform

Bare metal

### Description

I'm getting restrict-node-selection/restrict-nodename warning even when I set nodeName as null

    securityContext:
      capabilities:
        drop:
        - CAP_NET_RAW
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      runAsUser: 1000
    nodeName: null

### Steps to reproduce

1. 

### Expected behavior

Warning should NOT come

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by curiousperson101** [comment]
I've already applied fix mentioned in https://github.com/kyverno/policies/issues/529

**Comment by chipzoller** [comment]
Why are you defining the field and setting it to `null`? The policy expects the field to be absent.

**Comment by curiousperson101** [comment]
I also tried removing the field. It also didn't work.

**Comment by chipzoller** [comment]
Please show the full policy you're using and a test which shows it doesn't work.

**Comment by curiousperson101** [comment]
- Policy
`apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-node-selection
  annotations:
    policies.kyverno.io/title: Restrict node selection
    policies.kyverno.io/category: Sample
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      The Kubernetes scheduler uses complex logic to determine the optimal placement
      for new Pods. Users who have access to set certain fields in a Pod spec
      may sidestep this logic which in many cases is undesirable. This policy
      prevents users from targeting specific Nodes for scheduling of Pods by
      prohibiting the use of the `nodeSelector` and `nodeName` fields.
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: restrict-nodeselector
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: Setting the nodeSelector field is prohibited.
      pattern:
        spec:
          X(nodeSelector): "null"
  - name: restrict-nodename
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      all:
      - key: "{{request.operation || 'BACKGROUND'}}"
        operator: Equals
        value: CREATE
    validate:
      message: Setting the nodeName field is prohibited.
      pattern:
        spec:
          X(nodeName): "null"`


- Deployment
`apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: ubuntu
  labels:
    app: ubuntu
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - image: ubuntu:20.04
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu
    resources:
      limits:
        memory: "6400Mi"
      requests:
        cpu: "500m"
        memory: "6400Mi"
    securityContext:
      capabilities:
        drop:
        - CAP_NET_RAW
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      runAsUser: 1000
  restartPolicy: Always`

**Comment by chipzoller** [comment]
Please fix the formatting to use a code block.

**Comment by curiousperson101** [comment]
Fixed the format.

**Comment by chipzoller** [comment]
Tested on `main` branch, set policy to `Enforce` mode and created your Pod. Pod creation was allowed with no blocking/warning behavior.

**Comment by curiousperson101** [comment]
Thanks.
