### ISSUE TITLE
Any sample policy for Istio Authorization policies

### ISSUE THREAD

**Issue by nischay30** [kyverno/policies#580]
I am trying to create a Kyverno policy for the Istio Authorization policy which enforces that "from" and "to" block should be present   , otherwise it should be rejected. 
And , each "To" block should have a port defined and each "From" block should only use "principals" and "requestPrincipals" and no "*" allowed. 

I have tried multiple ways but no luck so far. Any documentation or samples would help

**Comment by chipzoller** [comment]
Have you seen these?

https://kyverno.io/policies/?policytypes=Istio

**Comment by nischay30** [comment]
Yeah, had seen these and tried different combinations but couldn't really build a policy out of it

**Comment by nischay30** [comment]
Opened -https://github.com/kyverno/policies/issues/582
