### ISSUE TITLE
Add Quota policy error on apply

### ISSUE THREAD

**Issue by kuzmacska** [kyverno/policies#598]
Kyverno Version
`helm chart v3.0.0-alpha.2 with default values`

Kubernetes Version
1.25.x

Kubernetes Platform
EKS

Description

When applying the policy https://main.kyverno.io/policies/best-practices/add-ns-quota/add-ns-quota/  getting the error below: 
`admission webhook "validate-policy.kyverno.svc" denied the request: 
path: spec.rules[0].generate..: failed to get the Group Version Resource for kind LimitRange`

The policy works well using chart v2.7.2

**Comment by chipzoller** [comment]
Cannot reproduce on the same chart version on K8s 1.26.

**Comment by kuzmacska** [comment]
> Cannot reproduce on the same chart version on K8s 1.26.

works for me on 1.26 as well, weird

**Comment by chipzoller** [comment]
I also cannot reproduce on K8s 1.25.

**Comment by kuzmacska** [comment]
I reinstalled it on 1.25 and it worked this time. Weird, might be wrong values. We can close the issue, thanks.
