### ISSUE TITLE
Test with Kyverno's kuttl tool from `main`

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#647]
[Here](https://github.com/kyverno/policies/blob/96c8d13b9e4374fa4be68bf57f0f0b37ac3efb6a/.github/workflows/test.yml#L63) we are pinning to a specific versions whereas we should do this for `main` branch of Kyverno's fork of kuttl. While this generally isn't a good practice, in our case we control the code and infrequently update it. Having new changes automatically picked up rather than having to change multiple workflows which point to it will be helpful.

@mintbomb27 can you make this minor change, please?

**Comment by mintbomb27** [comment]
Sure! On it.
