### ISSUE TITLE
Remove `validate-v1-22-removals` rule from check-deprecated-apis policy

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#683]
### Kyverno Version

1.10.x

### Kubernetes Version

1.26.x

### Kubernetes Platform

EKS

### Description

Now that 1.22 is unsupported officially in the latest version of Kyverno, remove the `validate-v1-22-removals` rule from the check-deprecated-apis policy. This is also causing problems in some clusters with its checks for TokenRequest and SubjectAccessReview.

### Steps to reproduce

None

### Expected behavior

Remove rule

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
@mintbomb27, would you please knock this one out?

**Comment by mintbomb27** [comment]
Sure

**Comment by ledroide** [comment]
Hello @chipzoller 
This version of check-deprecated-apis raises an error when applying with Kyverno v1.10.1 regarding kind `policy/*/PodSecurityPolicy` :
```
$ kubectl apply -f https://github.com/kyverno/policies/raw/main/best-practices/check-deprecated-apis/check-deprecated-apis.yaml --dry-run=server 
Warning: Validation failure actions enforce/audit are deprecated, use Enforce/Audit instead.
Error from server: error when creating "https://github.com/kyverno/policies/raw/main/best-practices/check-deprecated-apis/check-deprecated-apis.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: path: spec.rules[0].match.any[0].kinds: the kind defined in the all match resource is invalid: unable to convert GVK to GVR for kinds policy/*/PodSecurityPolicy
``` 

I guess it's because of [line 37 in check-deprecated-apis.yaml](https://github.com/kyverno/policies/blob/main/best-practices/check-deprecated-apis/check-deprecated-apis.yaml#L37)

**Comment by chipzoller** [comment]
In versions of Kubernetes to which this policy is applied, there may need to be some removal of rules which aren't applicable such as the case you're raising. This isn't a "bug" because that rule is applicable to versions prior to v1.25 when PSP was enabled, so we don't want to remove it from the policy.
