### ISSUE TITLE
Require NetworkPolicy

### ISSUE THREAD

**Issue by sowmyananjundappa** [kyverno/policies#695]
Problem Statement
The current require-network-policy  -  urlPath API call is wrong, policy results with below error 

Error
E0724 14:32:14.193513    9415 engine.go:255] engine.validate "msg"="failed to load context" "error"="failed to execute APICall: failed to substitute variables in context entry policies_count /apis/networking.k8s.io/v1/namespaces/{{request.namespace}}/networkpolicies: failed to resolve request.namespace at path /urlPath: JMESPath query failed: Unknown key \"namespace\" in path" "new.kind"="Deployment" "new.name"="application-name" "new.namespace"="app-namespace" "policy.apply"="All" "policy.name"="require-network-policy" "policy.namespace"="" "rule.name"="require-network-policy"

policy : "https://kyverno.io/policies/other/require-netpol/require-netpol/"

Example "Good" Resource
No response

Example "Bad" Resource
No response

Other Comments
No response

Slack discussion
No response

Troubleshooting
 I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
 I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
The path is correct. The `request.namespace` variable is not being substituted for some reason. Try `request.object.metadata.namespace` instead.

**Comment by sowmyananjundappa** [comment]
`request.object.metadata.namespace`  results in an "failed to execute APIcall" error

E0724 17:10:06.196226   12721 engine.go:255] engine.validate "msg"="failed to load context" "error"="failed to execute APICall: failed to  resource with raw url\n: /apis/networking.k8s.io/v1/namespaces/app-namespace/networkpolicies: method not supported: " "new.kind"="Deployment" "new.name"="appplication-name" "new.namespace"="app-namespace" "policy.apply"="All" "policy.name"="audit-networkpolicy" "policy.namespace"="" "rule.name"="namespace-needs-networkpolicy"

I tried to  test the API call by running below command
 `kubectl get --raw /apis/networking.k8s.io/v1/networkpolicies | jq .items`
 
 output is nested json format of existing policies in the cluster

**Comment by chipzoller** [comment]
Both calls work. Your call will get NetworkPolicies across the entire cluster, the call in the policy only gets those specific to a Namespace. 

```
method not supported
```

I've never seen this message. What version of K8s are you on?

**Comment by sowmyananjundappa** [comment]
Kubernetes version - 1.25
Kyverno Version: 1.10.0

**Comment by chipzoller** [comment]
No response, closing.
