### ISSUE TITLE
Update paths in artifact hub metadata files

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#703]
After PR #700 we now need to go and update all the `artifacthub-pkg.yml` files in each subdirectory under `other` to adjust the path in the `install` field.

**Comment by prady0t** [comment]
On it 👍🏻

**Comment by prady0t** [comment]
There are over 170 files named `artifacthub-pkg.yml`. It's notoriously difficult to change each of them one by one.

**Comment by chipzoller** [comment]
The only ones which need to be changed are those in the `other` directory.

**Comment by prady0t** [comment]
Yeah there are total 168 files named `artifacthub-pkg.yml` inside `other`.

**Comment by chipzoller** [comment]
It could be scripted. There was a past PR not too long ago by a mentee who used a script to generate them in the first place.

**Comment by prady0t** [comment]
Yes that's what I was thinking about.
