### ISSUE TITLE
"run interrupted" or "run uninterrupted"?

### ISSUE THREAD

**Issue by al-x** [kyverno/policies#748]
https://github.com/kyverno/policies/blob/2716d5964f706bbddf42b72933c72be081acd764/karpenter/add-karpenter-donot-evict/add-karpenter-donot-evict.yaml#L17

**Comment by chipzoller** [comment]
Crap, thanks, should be "uninterruped". Would you like to submit a minor PR for this? Please see the note [here](https://github.com/kyverno/policies#contribution) if so:

> When updating a policy already in the library, calculate the new sha256 sum of the changed policy and update the artifacthub-pkg.yml file's digest field with this value. This is to ensure Artifact Hub picks up the changes once merged.
