### ISSUE TITLE
Verify Image

### ISSUE THREAD

**Issue by lahirushanaka** [kyverno/policies#767]
Hello Team, 
We have deploy kyverno on private subnet in EKS , that mean we dont have the internet access. Also we use private ECR repo. We use cosign to sign the image with kms and we use similar policy. Could you please help use understand why we get  error. what are the solution you suggest us to implement for image verification.

`updating to TUF remote mirror: tuf: failed to download 8.root.json: Get "https://tuf-repo-cdn.sigstore.dev/8.root.json": dial tcp 34.117.62.14:443: i/o timeout
	remote status:{
		"mirror": "https://tuf-repo-cdn.sigstore.dev",
		"metadata": {}
	}
 >
I0`

**Comment by chipzoller** [comment]
I believe you have asked this on Slack [here](https://kubernetes.slack.com/archives/CLGR9BJU9/p1695363064424669) or someone from your team.
