### ISSUE TITLE
Add Quota

### ISSUE THREAD

**Issue by Zy-cc-bb** [kyverno/policies#791]
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-ns-quota
spec:
  rules:
  - name: generate-resourcequota
    match:
      any:
      - resources:
          kinds:
          - Namespace
    generate:
      apiVersion: v1
      kind: ResourceQuota
      name: default-resourcequota
      synchronize: true
      namespace: "{{request.object.metadata.name}}"
      data:
        spec:
          hard:
            requests.cpu: '?*'
            requests.memory: '?*'
            limits.cpu: 'limits.cpu*4'
            limits.memory: 'limits.memory*4Gi'
			services.nodeports: "0"

**Comment by chipzoller** [comment]
What are you attempting to convey here? Closed until it can be determined.
