### ISSUE TITLE
[Sample] Add require-run-as-nonroot policy that use CEL expressions

### ISSUE THREAD

**Issue by MariamFahmy98** [kyverno/policies#824]
### Problem Statement

Currently, all PSS policies are written in CEL expressions except the `require-run-as-nonroot` policy. We need to include it as well.  

Refer to [this](https://github.com/kyverno/policies/pull/776#issuecomment-1838426928) comment, for more information.

### Solution Description

N/A

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
The Slack thread in reference seems to be [here](https://kubernetes.slack.com/archives/C02TTBG6LF4/p1701685892590509), but I don't see any follow-up on your part. Would like to see how we can resolve and get this in with the objective being the complete set of PSS policies implemented as CEL subrules.

**Comment by jayme-github** [comment]
I've re-added @MariamFahmy98 's policy from https://github.com/kyverno/policies/pull/776/commits/853bff9368a3304ad7f6fd8c936c4cbe3fa95132#diff-3416b7bb0c4cce31c5d5833e936ec552ea9d1426fadb6f2ec3b81bce4cb910a8 together with tests from `pod-security/restricted/require-run-as-nonroot/` and it passes all tests for me. Maybe this was just a glitch in kuttl?
