### ISSUE TITLE
Unique Ingress Host and Path does not allow updating existing ingress

### ISSUE THREAD

**Issue by reegnz** [kyverno/policies#833]
https://main.kyverno.io/policies/other/s-z/unique-ingress-host-and-path/unique-ingress-host-and-path/

The policy ensures that no new conflicts are added to the list of ingresses.
It is however doing too good of a job, because it also blocks updating existing ingresses.
Eg. when modifying annotations on an ingress, this policy will block the changes.

Suggestion:
If the operation is an update, exclude the updated resource from the list that is compared against.

**Comment by chipzoller** [comment]
This may actually be a bug in Kyverno that we recently found and fixed and will be included in 1.11.2. See https://github.com/kyverno/kyverno/issues/8837. If you had an existing Ingress which was in violation of the policy set to `Enforce` and you tried to modify annotations and saw that attempt blocked, that's what you were hitting. If that doesn't describe your scenario then please explain further.

**Comment by reegnz** [comment]
Cool, thanks for that context @chipzoller! We'll verify once that version is released.

**Comment by chipzoller** [comment]
1.11.2 is now available.

**Comment by chipzoller** [comment]
Please comment if issue still present after testing.

**Comment by Fauli** [comment]
Hello  @chipzoller 

I'm using v1.12.3, and am still facing this issue. Not sure if it was ever resolved for @reegnz?
My policy is the stadard one from the documentation:
https://kyverno.io/policies/other/unique-ingress-host-and-path/unique-ingress-host-and-path/

Upon editing an existing ingress, I face:
```
unique-ingress-host-and-path:
  check-host-path-combo: 'validation failure: The Ingress host and path combination
    must be unique across the cluster.'
```

Do you know if this has ever been fixed and tested?
