### ISSUE TITLE
Require NetworkPolicy report error message after deployment

### ISSUE THREAD

**Issue by Axxy12** [kyverno/policies#838]
Hello,
When I´m trying to appliying the policy it shows an error message:  "failed to check deny conditions: failed to substitute variables in condition key: failed to resolve policies_count at path : JMESPath query failed: Unknown key "policies_count" in path"

It seems that there is a general bug in the policy.

Happy for any advice / support on that.

**Comment by chipzoller** [comment]
Please use the correct issue template to report a suspected policy bug.
