### ISSUE TITLE
[Bug] Cpol: require-network-policy

### ISSUE THREAD

**Issue by Axxy12** [kyverno/policies#839]
### Kyverno Version

1.10.x

### Kubernetes Version

1.26.x

### Kubernetes Platform

EKS

### Description

Hello,
When I´m trying to appliying the policy it shows an error message: "failed to check deny conditions: failed to substitute variables in condition key: failed to resolve policies_count at path : JMESPath query failed: Unknown key "policies_count" in path"

It seems that there is a general bug in the policy.

Happy for any advice / support on that.

### Steps to reproduce

1. Apply the policy.
2. After deployment the policy marked as error in the cluster.
-> key: failed to resolve policies_count at path : JMESPath query failed: Unknown key "policies_count" in path

**Error Message:**
  Policy:     require-network-policy
  Resources:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         xy
    Namespace:    xy
    UID:          e01c368b-e47a-48a2-a11e-15787591da76
  Result:         error
  Rule:           require-network-policy
  Scored:         true
  Source:         kyverno
  Timestamp:
    Nanos:    0
    Seconds:  1699462834
  Message:    failed to check deny preconditions: failed to substitute variables in condition key: failed to resolve policies_count at path : failed to execute APICall: failed to apply JMESPath items[?label_match(spec.podSelector.matchLabels, request.object.spec.template.metadata.labels)] | length(@) for context entry policies_count: Invalid type for: <nil>, expected: []jmespath.JpType{"object"}

**Defined Network Policy**
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: xy
  namespace: xy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: xy
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: abc

### Expected behavior

poilicy_count should check that a network policy is devined for each deployment. 

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Please describe the steps you're taking to check these results. This policy is not enabled for background scanning, which means Deployments created AFTER the time at which this policy is installed should be checked to ensure they have a matching NetworkPolicy.

**Comment by Axxy12** [comment]
Hello @chipzoller ,

the following steps are executed:
1. helm install kyverno 
2. kubectl apply -f require-network-policy.yaml (exact file from the kyverno webpage)
3. helm install kube-state-metrics (with a networkpolicy present in the helm chart)
4. kubectl get policyreports
5. kubectl describe policyreports

-> Message:   essage:    failed to check deny conditions: failed to substitute variables in condition key: failed to resolve policies_count at path : JMESPath query failed: Unknown key "policies_count" in path
  Policy:     require-network-policy
  Resources:
    API Version:  apps/v1
    Kind:         Deployment
    Name:         xyz
    Namespace:    xyz
    UID:          890836cb-0cca-4809-8923-183e6c8f7eeb
  Result:         error
  Rule:           require-network-policy
  Scored:         true
  Source:         kyverno
  Timestamp:
    Nanos:    0
    Seconds:  1702042600
  Category:   Sample

**Comment by chipzoller** [comment]
You must not be enabling the NetworkPolicy in the chart. If it is the one [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml#L213-L214), it is disabled by default. In following your steps but enabling the NetworkPolicy, the resulting PolicyReport shows a pass.

```sh
helm install ksm prometheus-community/kube-state-metrics --set networkPolicy.enabled=true
NAME: ksm
LAST DEPLOYED: Wed Dec 13 18:01:49 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
kube-state-metrics is a simple service that listens to the Kubernetes API server and generates metrics about the state of the objects.
The exposed metrics can be found here:
https://github.com/kubernetes/kube-state-metrics/blob/master/docs/README.md#exposed-metrics

The metrics are exported on the HTTP endpoint /metrics on the listening port.
In your case, ksm-kube-state-metrics.default.svc.cluster.local:8080/metrics

They are served either as plaintext or protobuf depending on the Accept header.
They are designed to be consumed either by Prometheus itself or by a scraper that is compatible with scraping a Prometheus client endpoint.
(⎈|k3d-kyverno:N/A)➜  kyverno-working git:(master) ✗ k get netpol
NAME                     POD-SELECTOR                                                               AGE
ksm-kube-state-metrics   app.kubernetes.io/instance=ksm,app.kubernetes.io/name=kube-state-metrics   4s
(⎈|k3d-kyverno:N/A)➜  kyverno-working git:(master) ✗ k get polr -w
NAME                                   PASS   FAIL   WARN   ERROR   SKIP   AGE
88b213aa-4fb5-412c-8b7d-618371ae6945   1      0      0      0       0      0s

```
