### ISSUE TITLE
Drop CAP_NET_RAW

### ISSUE THREAD

**Issue by computas-mle** [kyverno/policies#852]
Hi,

Could be missing something here, but isn't the policy as defined here wrong? 
It seems to be checking for the manifest dropping CAP_NET_RAW, when as I understand it from the Kubernetes docs, it should drop NET_RAW (i.e. without the CAP part). This seems to match with our own use of this policy where it will only stop failing my manifest if I drop CAP_NET_RAW, not NET_RAW.

Happy to be proven wrong, but thought I would mention it in case it helps. 

-Malcolm Lea

**Comment by chipzoller** [comment]
We've gone back and forth about this. Technically both `CAP_NET_RAW` and `NET_RAW` invoke the same "thing". We previously found that the former was more common than the latter. It can be customized to your preference.

**Comment by computas-mle** [comment]
Thanks for the quick reply - that helps :)
