### ISSUE TITLE
Require Run As Non-Root User

### ISSUE THREAD

**Issue by mthbrown** [kyverno/policies#855]
The rule allows `runAsUser` to not be set. However, this means that there are no assurances that the container does not run as `root`. So the rule isn't accurate. Making `runAsUser` required would fix this

**Comment by chipzoller** [comment]
The policy is implemented according to the definition set forth in the [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted):

![image](https://github.com/kyverno/policies/assets/29008123/b47f3ab7-b1b3-4384-86e4-de0b3427967c)
