### ISSUE TITLE
Require NetworkPolicy

### ISSUE THREAD

**Issue by Marwanoio** [kyverno/policies#856]
-Getting this error :
Error: INSTALLATION FAILED: parse error at (fix-kyverno-policies/templates/default/require-network-policy.yaml:31): function "request" not defined

-after running this command 
helm install kyverno-policies .

---require-network-policy.yaml
`{{- $name := "require-network-policy" }}
{{ if not (and $name .Values.disableDefaultTemplates) }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-network-policy
  annotations:
    policies.kyverno.io/title: Require NetworkPolicy
    policies.kyverno.io/category: Sample
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kyverno-version: 1.6.2
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Deployment, NetworkPolicy
    policies.kyverno.io/description: >-
      NetworkPolicy is used to control Pod-to-Pod communication
      and is a good practice to ensure only authorized Pods can send/receive
      traffic. This policy checks incoming Deployments to ensure
      they have a matching, preexisting NetworkPolicy.      
spec:
  validationFailureAction: audit
  background: false
  rules:
  - name: require-network-policy
    match:
      any:
      - resources:
          kinds:
          - Deployment
    preconditions:
      any:
      - key: "{{request.operation || 'BACKGROUND'}}"
        operator: Equals
        value: CREATE
    context:
    - name: policies_count
      apiCall:
        urlPath: "/apis/networking.k8s.io/v1/namespaces/{{request.namespace}}/networkpolicies"
        jmesPath: "items[?label_match(spec.podSelector.matchLabels, `{{request.object.spec.template.metadata.labels}}`)] | length(@)"
    validate:
      message: "Every Deployment requires a matching NetworkPolicy."
      deny:
        conditions:
          any:
          - key: "{{policies_count}}"
            operator: LessThan
            value: 1
`
 

 Chart.yaml

`apiVersion: v2
name: fix-kyverno-policies
description: A Helm chart that provisions Kyverno including the custom rules to test
type: application
version: 0.1.3
appVersion: "0.1.4"
condition: kyverno.enabled`

------  values.yaml
`# Global template settings
validationFailureAction: Audit

# Default template settings
disableDefaultTemplates: false

# Optional template settings
enableOptionalTemplates: 
`

**Comment by chipzoller** [comment]
https://kyverno.io/docs/writing-policies/variables/#variables-in-helm

**Comment by Marwanoio** [comment]
> https://kyverno.io/docs/writing-policies/variables/#variables-in-helm
{{ request.operation == 'CREATE' && resources[kind=='NetworkPolicy'].length > 0 && resources[kind=='NetworkPolicy'].spec.podSelector.matchLabels == request.object.spec.template.metadata.labels }}"

i cannot do this line
/
