### ISSUE TITLE
Variables in Helm 

### ISSUE THREAD

**Issue by Marwanoio** [kyverno/policies#858]
### Kyverno Version

1.6.x

### Kubernetes Version

1.20.x

### Kubernetes Platform

EKS

### Description

[https://github.com/kyverno/policies/issues/856](url)    
 
how can i avoid Helm interpreting Kyverno policies containing variables which  deployed through Helm   as Helm variables.

{{ request.operation == 'CREATE' && resources[kind=='NetworkPolicy'].length > 0 && resources[kind=='NetworkPolicy'].spec.podSelector.matchLabels == request.object.spec.template.metadata.labels }}"

### Steps to reproduce

1. [syntax highlighting](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)

### Expected behavior

solve the error

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Not a policies issue. Please use a discussion of Slack thread.
