### ISSUE TITLE
Disallow CRI socket mounts

### ISSUE THREAD

**Issue by ossie-git** [kyverno/policies#861]
I'd recommend adding both of these as, without them, the rule can easily be bypassed by mounting any of the following:

* `/var`
* `/var/run`

**Comment by chipzoller** [comment]
Probably makes more sense to just add this as a sentence in the description and for users to select an additional policy such as [this](https://kyverno.io/policies/other/limit-hostpath-vols/limit-hostpath-vols/) to complement the disallow CRI sockets policy.

**Comment by ossie-git** [comment]
Ideally, users would use an "allow list" and should use the "Limit hostPath Volumes to Specific Directories" and should never use the "Disallow CRI socket mounts" . However, not all users are at that stage and many may still want to use a "deny list". For users who select to do so, I think it makes more sense to actually make this policy do what it claims to do (block CRI socket mounts) instead of going half-way and just blocking some of the paths.
