### ISSUE TITLE
Cleanup Bare Pods

### ISSUE THREAD

**Issue by ossie-git** [kyverno/policies#867]
Is there a specific reason why **naked pods** (such as in [this](https://kyverno.io/policies/other/prevent-naked-pods/prevent-naked-pods/)) policy are referred to as **bare pods**? I think that unifying the naming would be better

**Comment by chipzoller** [comment]
It was just a name I came up with since there didn't seem to be an "official" name for this.

**Comment by ossie-git** [comment]
I was referring to [this](https://kyverno.io/policies/cleanup/cleanup-bare-pods/cleanup-bare-pods/) policy. From my understanding, this is the same as what a **naked** pod is (which was mentioned in the link above). Since they are both the same thing, why not stick to one name instead of two?

**Comment by chipzoller** [comment]
We can update the names.
