### ISSUE TITLE
Covering all Sample Policies

### ISSUE THREAD

**Issue by viveksahu26** [kyverno/policies#88]
In the current scenario, there are many [sample policies](https://github.com/kyverno/policies/tree/main/other) which requires to add `test.yaml` and `resource.yaml` for each of them in a separate folder under [other repo](https://github.com/kyverno/policies/tree/main/other) only.

**Comment by viveksahu26** [comment]
Hey @realshuting, can you assign me this issue.

**Comment by viveksahu26** [comment]
Hey @chipzoller , Do I need to cover those sample policies whose values are dependent on Admission Review data.

**Comment by realshuting** [comment]
> Hey @chipzoller , Do I need to cover those sample policies whose values are dependent on Admission Review data.

@viveksahu26 - as discussed, we don't need to pass in any value if the variable is defined for `request.object`. Other than this, we can specify these variables in `test.yaml`.
