### ISSUE TITLE
[Bug] Include explicit skipBackgroundRequests in policies

### ISSUE THREAD

**Issue by jemag** [kyverno/policies#896]
### Kyverno Version

1.11.x

### Kubernetes Version

1.27.x

### Kubernetes Platform

AKS

### Description

(Kyverno version is actually `1.11.x`, it is just not available as an option in the dropdown)

Policies currently do not explicitly set the property `skipBackgroundRequests` which by default will be set to `true`. This causes issues with server-side apply and ArgoCD, since the property will be set to true automatically and ArgoCD will always be out of sync trying to remove it.

While this property can be ignored using the `ignoreDifferences` mechanism, this can be annoying for situations where you actually want to change the `skipBackgroundRequests` value and it is no longer taken into account. I think this would provide a better out-of-the-box experience for ArgoCD users.

See https://github.com/argoproj/argo-cd/issues/11139 for more information

### Steps to reproduce

1. Install ArgoCD
2. Configure application with server-side apply for synchronizing kyverno policies
3. Synchronize a policy like https://raw.githubusercontent.com/kyverno/policies/release-1.11/other/res/restrict-ingress-defaultbackend/restrict-ingress-defaultbackend.yaml
4. Notice ArgoCD is always out of sync trying to sync the ClusterPolicy

### Expected behavior

Property is included in the policies and ArgoCD syncs properly.

### Screenshots

![image](https://github.com/kyverno/policies/assets/7985687/72499a54-a590-498d-b27a-c1959d48018c)

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
The policy library isn't really designed for folks to directly sync a policy into their systems using a GitOps controller. Going and adding all the fields which are defaulted in the CRD (there's more than `skipBackgroundRequests`) is not only an untenable task but effectively bumps compatibility for all the policies in the library. Performing that defaulting on just the versions effected would make more sense but still seems unnecessary.

**Comment by pre** [comment]
I came here to open this precise issue with ArgoCD server side apply, but ..

**Comment by marbon87** [comment]
If the templates should not be used as is, why is there a helm-chart available?
