### ISSUE TITLE
[Bug] require-unique-uid-per-workload policy takes long time to execute

### ISSUE THREAD

**Issue by truongnht** [kyverno/policies#903]
### Kyverno Version

1.10.x

### Kubernetes Version

1.27.x

### Kubernetes Platform

EKS

### Description

Require-unique-uid-per-workload policy is added to our cluster which has quite some workloads. We observe with more workload the chance we got into `kyverno mutating timeout issue` is higher.

```Internal error occurred: failed calling webhook "mutate.kyverno.svc-fail": failed to call webhook: Post "[https://kyverno-svc.kyverno.svc:443/mutate/fail?timeout=10s](https://kyverno-svc.kyverno.svc/mutate/fail?timeout=10s)": context deadline exceeded```

### Steps to reproduce

1. Install the policy in cluster with high workload. 
2. Trigger a deployment
3. Observe the log for failure

### Expected behavior

Error would not occur

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Because this asks the API server for server-side filtering of ALL Pods, you may want to avoid using this on heavily loaded clusters because of the performance requirement. There's unfortunately not a better way to go about this and still achieve the objective.

**Comment by truongnht** [comment]
@chipzoller , thanks for quick reply. I did turn on the tracing and observed that the api call to get all pods only take small amount of time. Majority would then be on comparing the UID (I guess). Please correct me if I am wrong there.

![image](https://github.com/kyverno/policies/assets/3480830/61a1c693-a3fe-4862-8b20-c0505151be76)

**Comment by chipzoller** [comment]
You may want to try this on Kyverno 1.11 latest patch. I know we've made some significant performance improvements in situations just like this.

**Comment by truongnht** [comment]
can you explain how it has been improved?

**Comment by chipzoller** [comment]
Internally the storing of variables which are very large has been improved so they can be processed quicker and with fewer resources.

**Comment by truongnht** [comment]
awesome, also my thought that some processings have been repeated in each comparison. Will keep you posted

**Comment by truongnht** [comment]
We have been in 1.11.1 when this issue occurs. Unfortunately bumping to 1.11.4 does not improve much

**Comment by truongnht** [comment]
unofficially yes, may I know when 1.12 will be released?

**Comment by chipzoller** [comment]
No committed release date.
