### ISSUE TITLE
Add a policy which uses `regex_replace_all` 

### ISSUE THREAD

**Issue by NoSkillGirl** [kyverno/policies#91]
see: https://kubernetes.slack.com/archives/CLGR9BJU9/p1628006140065200

Add the policy mentioned [here](https://kubernetes.slack.com/archives/CLGR9BJU9/p1628093711112600?thread_ts=1628006140.065200&cid=CLGR9BJU9) in the sample policies and website as an example of `regex_replace_all`.

**Comment by chipzoller** [comment]
This is blocked due to issue https://github.com/kyverno/kyverno/issues/2243

**Comment by chipzoller** [comment]
Milestone in corresponding issue for 1.5.3

**Comment by chipzoller** [comment]
Done
