### ISSUE TITLE
[Enhancement] Move PSS CEL test resources inside folders

### ISSUE THREAD

**Issue by chipzoller** [kyverno/policies#933]
### Kyverno Version

1.10.x

### Kubernetes Version

1.27.x

### Kubernetes Platform

Other (specify in description)

### Description

CEL PSS policies reference test resources outside of their parent folders. This is brittle and not ideal as they use relative paths and will break if either is moved.

### Steps to reproduce

1. 

### Expected behavior

Policies should have tests with all referenced resources available in the policy folder. Different tests for the same policy may reference resources in other folders within the parent policy folder but not outside.

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
cc @Chandan-DK

**Comment by Chandan-DK** [comment]
@MariamFahmy98 I'd like to work on this
