### ISSUE TITLE
[Sample] policy to check if prometheus is configured or not 

### ISSUE THREAD

**Issue by swastik959** [kyverno/policies#943]
### Problem Statement

many resource recommendation tools such as goldilocks and krr requires prometheus to be configured 

### Solution Description

A policy which checks if prometheus is configured or not 

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
Two reasons why I don't think this is worth trying to write a policy:

1. Prometheus is an infrastructure concern and not an app dependency like Pod controllers are to a VPA. Cluster operators are going to know whether Prometheus is installed or not and won't look to a policy engine.
2. Prometheus can be installed and configured in thousands of ways, with custom names, even with multiple instances per cluster. There's no good way to determine if Prometheus is installed let alone configured or not.

**Comment by JimBugwadia** [comment]
Agreed, closing.
