### ISSUE TITLE
Prepend Image Registry policy should not apply on `UPDATE` for `initContainers`

### ISSUE THREAD

**Issue by ShaylanDias** [kyverno/policies#954]
In the example policy `prepend-image-registry` the policy matches on `request.operation == UPDATE`:
https://github.com/kyverno/policies/blob/c1e882a748b0f6a9a0c38af7aaeed78c612f1fff/other/prepend-image-registry/prepend-image-registry.yaml#L55

This causes errors when the policy is added to an existing Kubernetes cluster. Let's say we have a Pod with an Init Container that matches the rule but exists prior to the policy being added. If the pod is updated for something else (e.g. a label), then it will attempt to update the Init Container's image as well and fail to apply the update as a whole since Init Containers cannot be updated. For this reason, I don't believe it makes sense to have the rule match on `UPDATE` for Init Containers at all

**Comment by chipzoller** [comment]
Why close this? It seems legitimate to me.

**Comment by ShaylanDias** [comment]
> Why close this? It seems legitimate to me.

@chipzoller My bad, I'd meant to write a comment. I closed it because when I investigated a little further it seemed like in some cases a pod can have its `initContainers.*.images` updated and in some cases not? I'm not super familiar with this though so will defer judgement.

**Comment by ShaylanDias** [comment]
I investigated further and can confirm that the problems I was seeing were related to Istio reordering containers and causing an error by updating other immutable values (as seen here: https://github.com/kyverno/kyverno/issues/9863#issuecomment-1981997608) rather than the failure being due to `UPDATE` requests on Init Containers. The error output I received also makes it clear that `spec.initContainers[*].image` should be safe to update:

```
The Pod <redacted> is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
```
