### ISSUE TITLE
 Refactoring the chainsaw tests on cert-manager/limit-dnsnames

### ISSUE THREAD

**Issue by mohamedasifs123** [kyverno/policies#958]
Refactoring the chainsaw tests on cert-manager/limit-dnsnames

**Comment by chipzoller** [comment]
Why?

**Comment by mohamedasifs123** [comment]
Due to the issue #950, some tests are need to be refactored.

**Comment by chipzoller** [comment]
Don't need a new issue since one exists. Just reference that issue in your PR.
