### ISSUE TITLE
[Sample] Best Practices for PDBs

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/policies#969]
### Problem Statement

This KubeCon presentation had some great best practices for PDBs:

**Building Resilient Services on Kubernetes - Todd Ekenstam, Intuit & Anusha Ragunathan, Intuit Inc**

https://youtu.be/lTi4cu0T7XY?t=1400

Would be good to add sample policies for these.

### Solution Description

Add policies for:

<img width="518" alt="image" src="https://github.com/kyverno/policies/assets/5489990/45768384-42ab-4cfa-9e14-e3ae990d7f3b">

### Troubleshooting

- [X] I have read and followed the documentation AND the [troubleshooting guide](https://kyverno.io/docs/troubleshooting/).
- [X] I have verified the policy does not exist in the [samples library](https://kyverno.io/policies/).

**Comment by chipzoller** [comment]
Based on [what we already have](https://main.kyverno.io/policies/?policytypes=PodDisruptionBudget), what do you think is a specific gap?

**Comment by JimBugwadia** [comment]
@fast-n-curious - what are the next steps here? Are there any updates required, or should we close this?

**Comment by fast-n-curious** [comment]
@JimBugwadia I have created a draft for a blog to cover this and the Kyverno policies that support the cases mentioned by Todd. Will share that here with the community (along with the wider audience).

**Comment by JimBugwadia** [comment]
Ok, closing the issue.

If you want to publish as a Kyverno blog please raise a PR in the website repo.
