### ISSUE TITLE
`background: false` is specified even though it is not required.

### ISSUE THREAD

**Issue by sotoiwa** [kyverno/policies#97]
In some sample policies, `background: false` is specified even though it is not required.  The following are some examples.

- https://github.com/kyverno/policies/blob/main/best-practices/restrict_image_registries/restrict_image_registries.yaml#L18
- https://github.com/kyverno/policies/blob/main/other/imagepullpolicy-always.yaml#L17
- https://github.com/kyverno/policies/blob/main/other/restrict_annotations.yaml#L18
- https://github.com/kyverno/policies/blob/main/other/restrict_controlplane_scheduling.yaml#L17
- https://github.com/kyverno/policies/blob/main/other/restrict_node_selection.yaml#L17

This is confusing and I think we should specify `background: false` only where necessary. Alternatively, we should explicitly specify whether the background attribute is true or false for all policies.

**Comment by chipzoller** [comment]
Makes sense, @sotoiwa, and I think would be a great contribution for you to make. Would you like to take this up and make the appropriate changes throughout the policies repo?

**Comment by sotoiwa** [comment]
@chipzoller  I'd like to update #101 to fix all policy but I need some discussion.

For all the validate rules, I'd like to state the `background` and `validationFailureAction` attributes. `background: true/false` should depending on whether background scanning is possible or not.

In the case `background: false`, do you think the `validationFailureAction` should be `enforce` or `audit`? Currently, most of the validate rules say `audit` like [this](https://github.com/kyverno/policies/blob/main/other/block-pod-exec-by-namespace-label.yaml), but a few say `enforce` like [this](https://github.com/kyverno/policies/blob/main/other/block_updates_deletes.yaml). I think `enforce` might be more appropriate since you can't `audit` by report if `background: false`.

Aslo, those attributes don't make sense for the mutate and generate rules. Should we put those attributes in samples? I think it's easier to understand that background scan can' be done if it says background: false. Currently, some rules says some says only `background: false` like [this](https://github.com/kyverno/policies/blob/main/other/add_volume_deployment.yaml)  and some says nothing like [this](https://github.com/kyverno/policies/blob/main/best-practices/add_safe_to_evict.yaml).

**Comment by chipzoller** [comment]
>For all the validate rules, I'd like to state the background and validationFailureAction attributes. background: true/false should depending on whether background scanning is possible or not.

Agree, this would be good to state explicitly.

>In the case background: false, do you think the validationFailureAction should be enforce or audit? Currently, most of the validate rules say audit like this, but a few say enforce like this. I think enforce might be more appropriate since you can't audit by report if background: false.

We have made a conscious decision to leave `validationFailureAction` set to `audit` so as not to cause unintended blocking of resources for users new to Kyverno who might like to try a policy but aren't yet sure what it'll do. We want to be as friction-less as possible as do no harm. For some of the policies, however, it makes no sense to have a policy not in `enforce` mode, but those are more the exception rather than the rule.

>Aslo, those attributes don't make sense for the mutate and generate rules. Should we put those attributes in samples? I think it's easier to understand that background scan can' be done if it says background: false. Currently, some rules says some says only background: false like this and some says nothing like this.

Yes, this would also be good to standardize upon. Looking forward to your updated PR :)
