### ISSUE TITLE
Add RoleBinding not working for EKS(aws k8s cluster)

### ISSUE THREAD

**Issue by chokhareganesh** [kyverno/policies#984]
Hey, I'm new at using policies, 

I referred Generating Bindings but its not working, 
- https://main.kyverno.io/policies/best-practices/add-rolebinding/add-rolebinding/
- https://kyverno.io/docs/writing-policies/generate/#generating-bindings

alternatively, I tried generating [ConfigMap](https://kyverno.io/docs/writing-policies/generate/#data-examples) which is working fine, Need help with it

**Comment by chipzoller** [comment]
Need more details here.

What steps did you go through? Be precise. What is the test process? And what are the results?

**Comment by chokhareganesh** [comment]
Hi @chipzoller , 

1. For installation followed [Install Kyverno using YAMLs](https://kyverno.io/docs/installation/methods/#install-kyverno-using-yamls)
2. For tagging k8s namespaces followed, [Auto-labeling Kubernetes resources with Kyverno ](https://www.cncf.io/blog/2020/12/30/auto-labeling-kubernetes-resources-with-kyverno/), **which worked perfectly**
3. However, for [Generating Bindings ](https://kyverno.io/docs/writing-policies/generate/#generating-bindings) it not worked
4. **For debugging**, [set logging to -v=6 ](kyverno-admission-controller-), then checked logs for kyverno-admission-controller deployment, but did not found any error

**Comment by chipzoller** [comment]
For step 3, did you do what the docs say? If so, please show the steps and the resources you created/modified along with your policy.

**Comment by chokhareganesh** [comment]
1. Created ClusterPolicy Resource 
```yaml

kubectl get ClusterPolicy steven-rolebinding -o yaml

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kyverno.io/v1","kind":"ClusterPolicy","metadata":{"annotations":{},"name":"steven-rolebinding"},"spec":{"rules":[{"generate":{"apiVersion":"rbac.authorization.k8s.io/v1","data":{"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"admin"},"subjects":[{"apiGroup":"rbac.authorization.k8s.io","kind":"User","name":"steven"}]},"kind":"RoleBinding","name":"steven-rolebinding","namespace":"{{request.object.metadata.name}}"},"match":{"any":[{"resources":{"kinds":["Namespace"]}}]},"name":"steven-rolebinding"}]}}
  creationTimestamp: "2024-05-03T13:14:04Z"
  generation: 1
  name: steven-rolebinding
  resourceVersion: "5952825"
  uid: 961ff121-e8e9-48eb-b101-3dbd8e3e85a5
spec:
  admission: true
  background: true
  rules:
  - generate:
      apiVersion: rbac.authorization.k8s.io/v1
      data:
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: admin
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: User
          name: steven
      kind: RoleBinding
      name: steven-rolebinding
      namespace: '{{request.object.metadata.name}}'
    match:
      any:
      - resources:
          kinds:
          - Namespace
    name: steven-rolebinding
    skipBackgroundRequests: true
  validationFailureAction: Audit
status:
  autogen: {}
  conditions:
  - lastTransitionTime: "2024-05-03T13:20:48Z"
    message: Ready
    reason: Succeeded
    status: "True"
    type: Ready
  ready: true
  rulecount:
    generate: 1
    mutate: 0
    validate: 0
    verifyimages: 0
  validatingadmissionpolicy:
    generated: false
    message: ""
```
2. Once this resource created, I tried creating k8s namespace 
```sh
kubectl create ns test3
```
3.  Get role-binding  (tried after few minutes as well)
```
kubectl get rolebinding -n test3
No resources found in test3 namespace.
```

**Comment by chipzoller** [comment]
From the docs:

>In order for Kyverno to generate a new RoleBinding or ClusterRoleBinding resource, its ServiceAccount must first be bound to the same Role or ClusterRole which you’re attempting to generate. If this is not done, Kubernetes blocks the request because it sees a possible privilege escalation attempt from the Kyverno background controller’s ServiceAccount. This particularity is not specific to Kyverno but rather how Kubernetes RBAC is designed to work.

Did you do this?

**Comment by chokhareganesh** [comment]
> From the docs:
> 
> > In order for Kyverno to generate a new RoleBinding or ClusterRoleBinding resource, its ServiceAccount must first be bound to the same Role or ClusterRole which you’re attempting to generate. If this is not done, Kubernetes blocks the request because it sees a possible privilege escalation attempt from the Kyverno background controller’s ServiceAccount. This particularity is not specific to Kyverno but rather how Kubernetes RBAC is designed to work.
> 
> Did you do this?

I think this ServiceAccount creation is taken via [Install Kyverno using YAMLs](https://kyverno.io/docs/installation/methods/#install-kyverno-using-yamls)), isn't it ? If no, then I did not followed creating and attaching ServiceAccount to Role/ClusterRole

Could I get doc reference for the same and if possible the doc you reffered in the above comment?

**Comment by chokhareganesh** [comment]
@chipzoller , I followed as you recommanded [Doc Link: Create a new ClusterRoleBinding for the Kyverno background controller’s ServiceAccount](https://kyverno.io/docs/writing-policies/generate/#generating-bindings) , It worked 
```
> kubectl get rolebinding -n test3    

NAME                  ROLE                AGE
test-3admin-binding   ClusterRole/admin   2m31s
```

Many Thanks @chipzoller , for providing quick responses over issue
